export type RecordField={key:string;label:string;type?:'text'|'email'|'tel'|'number'|'textarea'|'select';required?:boolean;options?:string[];max?:number};
export const recordModules:Record<string,{table:string;permission:string;fields:RecordField[]}>={
 partners:{table:'agents',permission:'agents',fields:[]},policies:{table:'policies',permission:'quotes_policies',fields:[]},
 customers:{table:'customers',permission:'crm',fields:[{key:'name',label:'Name',required:true,max:100},{key:'contact',label:'Mobile number',type:'tel'},{key:'email',label:'Email',type:'email',max:254}]},
 leads:{table:'leads',permission:'leads',fields:[{key:'name',label:'Name',required:true,max:100},{key:'contact',label:'Mobile number',type:'tel',required:true},{key:'priority',label:'Priority',type:'select',options:['low','medium','high']}]},
 'website-leads':{table:'website_quote_requests',permission:'leads',fields:[{key:'customer_name',label:'Name',required:true,max:100},{key:'mobile',label:'Mobile number',type:'tel',required:true}]},
 'claim-help':{table:'claim_help_requests',permission:'leads',fields:[{key:'name',label:'Name',required:true,max:100},{key:'whatsapp_number',label:'WhatsApp number',type:'tel',required:true},{key:'claim_amount',label:'Claim amount',type:'number',required:true},{key:'location',label:'Location',required:true,max:200},{key:'claim_failure_reason',label:'Claim failure reason',type:'textarea',required:true,max:4000},{key:'status',label:'Status',type:'select',options:['new','reviewing','contacted','resolved','closed']}]},
 'contact-requests':{table:'website_contact_requests',permission:'leads',fields:[{key:'name',label:'Name',required:true,max:100},{key:'mobile',label:'Mobile number',type:'tel',required:true},{key:'email',label:'Email',type:'email',max:254},{key:'state',label:'State',max:100},{key:'message',label:'Message',type:'textarea',required:true,max:4000},{key:'status',label:'Status',type:'select',options:['new','contacted','resolved','closed']}]}
};
