import {test,expect} from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';
for(const provider of ['email','google'])test(provider+' registration retains invite across reload and submits through the shared endpoint',async({page,context})=>{
 const code='b'.repeat(64);await context.addCookies([{name:'partner_invite',value:code,domain:'localhost',path:'/',httpOnly:true,sameSite:'Lax'}]);
 let calls=0;await page.route('**/api/partner/invitation',r=>r.fulfill({json:{invited:true,name:'Inviting Partner'}}));await page.route('**/api/partner/onboarding/start',r=>{calls++;expect(r.request().headers().cookie).toContain('partner_invite='+code);expect(r.request().headers().authorization).toBe('Bearer session-token');return r.fulfill({json:{data:{id:'new-agent'}}})});await page.route(/\/partner(?:\/complete-profile)?$/, r=>r.fulfill({contentType:'text/html',body:'<h1>Partner Dashboard</h1>'}));
 const compiled=ts.transpileModule(fs.readFileSync('src/components/website/partner-auth-supabase.tsx','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
 await page.route('**/__register_fixture',r=>r.fulfill({contentType:'text/html',body:'<div id="root"></div>'}));
 async function mount(){await page.goto('/__register_fixture');await page.addScriptTag({path:path.resolve('node_modules/react/umd/react.development.js')});await page.addScriptTag({path:path.resolve('node_modules/react-dom/umd/react-dom.development.js')});await page.addScriptTag({content:`const runtime={jsx:(t,p,k)=>React.createElement(t,{...p,key:k}),jsxs:(t,p,k)=>React.createElement(t,{...p,key:k}),Fragment:React.Fragment};const session={access_token:'session-token'};const modules={react:React,'react/jsx-runtime':runtime,'next/link':{__esModule:true,default:p=>React.createElement('a',p)},'next/image':{__esModule:true,default:p=>React.createElement('img',p)},'lucide-react':{},'@/lib/supabase-client':{finishOAuthPopup:()=>false,authenticatedDestination:async()=>'/partner',signInWithGoogle:async()=>session,supabaseAuth:{auth:{getSession:async()=>({data:{session:null}}),signUp:async()=>({data:{session}})}}}};const require=n=>modules[n];const out={};((exports)=>{${compiled}})(out);ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(out.PartnerAuthSupabase));`});await expect(page.getByText('Inviting Partner',{exact:true})).toBeVisible();}
 await mount();await page.reload();await mount();expect(await page.evaluate(()=>document.cookie)).not.toContain('partner_invite');
 if(provider==='google')await page.getByRole('button',{name:'Continue with Google',exact:true}).click();else{await page.getByLabel('Full name',{exact:true}).fill('New Partner');await page.getByLabel('Mobile number',{exact:true}).fill('9876543210');await page.getByLabel('Email address',{exact:true}).fill('new@example.test');await page.getByLabel('Password',{exact:true}).fill('Password123!');await page.getByLabel('Confirm password',{exact:true}).fill('Password123!');await page.getByRole('button',{name:'Create partner account'}).click();}
 await expect(page).toHaveURL(/\/partner(?:\/complete-profile)?$/);expect(calls).toBe(1);
});
