import {test,expect,type Page} from '@playwright/test';
import fs from 'node:fs';import path from 'node:path';import ts from 'typescript';import QRCode from 'qrcode';
const code='a'.repeat(64),base={code,canInvite:true,expiresAt:null,members:[],total:0,counts:[0,0,0],page:1};
async function mount(page:Page,theme='light'){
 const css=['src/app/appearance.css','src/app/partner/partner-dashboard.css','src/app/partner/partner-skeleton.css','src/app/partner/partner-team.css'].map(p=>fs.readFileSync(p,'utf8')).join('\n');
 await page.route('**/__team_fixture',r=>r.fulfill({contentType:'text/html',body:'<html data-theme="'+theme+'"><style>body{margin:0}*{box-sizing:border-box}'+css+'</style><div class="pd-shell"><main class="pd-content" id="root"></main></div></html>'}));await page.goto('/__team_fixture');
 await page.addScriptTag({path:path.resolve('node_modules/react/umd/react.development.js')});await page.addScriptTag({path:path.resolve('node_modules/react-dom/umd/react-dom.development.js')});
 const compile=(p:string)=>ts.transpileModule(fs.readFileSync(p,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,esModuleInterop:true}}).outputText;
 const qr=await QRCode.toDataURL('http://localhost:3100/invite/'+code,{width:600,margin:4});
 await page.addScriptTag({content:`const runtime={jsx:(t,p,k)=>React.createElement(t,{...p,key:k}),jsxs:(t,p,k)=>React.createElement(t,{...p,key:k}),Fragment:React.Fragment};const modules={react:React,'react/jsx-runtime':runtime,'lucide-react':new Proxy({},{get:()=>p=>React.createElement('svg',p)}),'@/lib/supabase-client':{accessToken:async()=>'test-token'},qrcode:{__esModule:true,default:{toDataURL:async()=>${JSON.stringify(qr)}}}};const require=n=>modules[n];const sk={};((exports)=>{${compile('src/components/partner/partner-skeleton.tsx')}})(sk);modules['./partner-skeleton']=sk;const team={};((exports)=>{${compile('src/components/partner/partner-team.tsx')}})(team);ReactDOM.createRoot(document.getElementById('root')).render(React.createElement(team.PartnerTeam));`});
}
for(const theme of ['light','dark'])for(const width of [390,1440])test('team invitations '+theme+' '+width,async({page})=>{
 await page.setViewportSize({width,height:900});await page.route('**/api/partner/team?*',r=>{expect(r.request().headers().authorization).toBe('Bearer test-token');return r.fulfill({json:base})});await mount(page,theme);
 await expect(page.getByRole('heading',{name:'Your team starts with one invitation'})).toBeVisible();await expect(page.getByLabel('Your invitation link')).toHaveValue('http://localhost:3100/invite/'+code);await expect(page.getByRole('link',{name:'Share via WhatsApp'})).toHaveAttribute('href',/https:\/\/wa.me\/\?text=/);await expect(page.getByRole('img',{name:/Scan to register/})).toBeVisible();
 const download=page.waitForEvent('download');await page.getByRole('button',{name:'Download QR',exact:true}).click();expect((await download).suggestedFilename()).toBe('magikpolicy-partner-invite.png');
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(theme==='dark')expect(await page.locator('.pt-card').first().evaluate(e=>getComputedStyle(e).backgroundColor)).toBe('rgba(0, 0, 0, 0)');await page.screenshot({path:'test-results/team-'+theme+'-'+width+'.png',fullPage:true});
});
test('team error retry, members and level filter',async({page})=>{
 let calls=0;await page.route('**/api/partner/team?*',r=>{calls++;return r.fulfill(calls===1?{status:500,json:{error:'Temporary failure'}}:{json:{...base,counts:[1,0,0],total:1,members:new URL(r.request().url()).searchParams.get('level')==='2'?[]:[{depth:1,member:{id:'one',agent_code:'MP-ONE',status:'draft',region:null,created_at:'2026-09-12',users:{full_name:'Test Partner'}}}]}})});await mount(page);await expect(page.getByRole('alert')).toContainText('Temporary failure');await expect(page.getByText('Your team starts with one invitation')).toHaveCount(0);await page.getByRole('button',{name:'Try again'}).click();await expect(page.getByText('Test Partner',{exact:true})).toBeVisible();await page.getByLabel('Team level').selectOption('2');await expect(page.getByText('No partners at this level',{exact:true})).toBeVisible();
});
