import Image from "next/image";
import Link from "next/link";
import { ShieldPlus, HeartPulse, Users, ClipboardCheck, Headphones, Zap, IndianRupee, CheckCircle2, ArrowRight } from "lucide-react";
import { WebsiteQuotation } from "./quotation-form";
import "./health-insurance-page.css";
const plans = [
 ["Individual cover", "A separate sum insured for one person. Compare benefits against your own health needs and budget."],
 ["Family floater", "A shared sum insured for eligible family members. Consider how a claim by one member affects the cover left for others."],
 ["Cover for parents", "Explore age-appropriate options, with particular attention to medical disclosures, co-payments and treatment limits."],
 ["Top-up cover", "Additional protection above a deductible. Check whether the threshold applies to each claim or to eligible claims added together."],
];
const checklist = [
 ["Sum insured", "Would the cover support treatment at hospitals you would actually use? Consider existing cover and the savings you can set aside."],
 ["Your share of a claim", "A co-payment is a percentage you pay; a deductible is an amount that applies before the insurer pays. Compare both."],
 ["Room and treatment limits", "Look for room-category restrictions and caps on specific treatments, rather than judging a plan by its headline cover alone."],
 ["Waiting periods", "Check when cover starts for illnesses, disclosed medical conditions and specific benefits. Not every benefit starts on day one."],
 ["Hospital access", "Confirm your preferred hospital is in the insurer's current cashless network. Ask about the approval process before admission."],
 ["Policy documents", "Read the Customer Information Sheet and policy wording together. Check exclusions, renewal terms and the claim procedure before paying."],
];
const faqs = [
 ["What does health insurance help pay for?", "Hospitalisation policies reimburse eligible medical expenses up to the available cover, subject to their terms. Outpatient consultations, maternity and other benefits are not automatically included; check the specific plan."],
 ["Is cashless treatment completely free?", "Cashless settlement means the insurer or its administrator pays the hospital for approved expenses. You may still need to pay excluded items, co-payments, deductibles or amounts beyond policy limits."],
 ["Can I apply with an existing medical condition?", "Disclose your medical history fully when applying. The insurer assesses the proposal and sets the applicable terms. Ask how your condition is treated under the offered cover before accepting it."],
 ["Is family cover always the better choice?", "There is no single answer for every household. Compare the shared cover available under a floater with separate policies, taking account of each member's age, medical needs and existing insurance."],
 ["Does requesting a quote start my insurance?", "No. This form asks the MagikPolicy team to contact you. Cover begins only according to the policy issued by the insurer, after its proposal and payment requirements are met."],
 ["What should I keep ready for a claim?", "Keep your policy details, claim form, bills, receipts, prescriptions, investigation reports and discharge summary. The insurer may request additional documents depending on the treatment and claim."],
];
export function HealthInsurancePage() {
 return <main className="health-page">
  <div className="health-top"><nav className="health-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/products">Insurance products</Link><span>/</span><span aria-current="page">Health Insurance</span></nav>
   <div className="health-hero-layout">
    <header className="health-hero"><div className="health-hero-copy"><p className="health-eyebrow">HEALTH INSURANCE</p><h1>Health Insurance<br />for a <span>Healthier You</span></h1><p className="health-lead">Make room for life, with health cover that fits your family. Explore your options, understand the details and take the next step with confidence.</p>
     <div className="health-hero-benefits"><div><span className="health-icon blue"><ShieldPlus aria-hidden="true" /></span><h2>Cashless<br />hospitalisation</h2><p>For approved care<br />at network hospitals</p></div><div><span className="health-icon green"><IndianRupee aria-hidden="true" /></span><h2>Cover for<br />your budget</h2><p>Compare benefits<br />alongside premiums</p></div><div><span className="health-icon purple"><ClipboardCheck aria-hidden="true" /></span><h2>Choice for<br />your family</h2><p>Individual and<br />shared-cover options</p></div></div>
    </div><div className="health-family"><div className="health-family-shape" /><Image src="/brand/magikpolicy-family-hero.png" alt="Parents embracing their daughter" width={1161} height={1354} priority sizes="(max-width: 700px) 80vw, (max-width: 1200px) 36vw, 26vw" /><div className="health-care-badge"><span><HeartPulse aria-hidden="true" /></span><p><strong>Care Today</strong><br />For a Brighter Tomorrow</p></div></div></header>
    <aside className="product-quotation-sidebar health-quote" aria-label="Request an insurance quote"><WebsiteQuotation /></aside>
   </div>
  </div>
  <section className="health-advantages" aria-labelledby="health-why"><div className="health-container"><h2 id="health-why">Why explore health cover with MagikPolicy?</h2><div className="health-advantage-grid">{[[Users,"Compare your options","Bring different benefits and costs into one clear conversation.","blue"],[CheckCircle2,"Understand your cover","Know what to look for in the insurer's policy documents.","green"],[Headphones,"Helpful guidance","Talk through your questions before choosing a plan.","blue"],[Zap,"A simple first step","Share your details and request a callback from our team.","orange"]].map(([Icon,title,copy,color])=>{const Symbol=Icon as typeof Users;return <article key={String(title)}><span className={"health-icon "+color}><Symbol aria-hidden="true" /></span><h3>{String(title)}</h3><p>{String(copy)}</p></article>;})}</div></div></section>
  <div className="health-container health-content">
   <nav className="health-jump-links" aria-label="Health insurance guide"><a href="#health-basics">The basics</a><a href="#health-plans">Plan types</a><a href="#health-cover">Coverage</a><a href="#health-compare">Compare plans</a><a href="#health-claims">Claims</a><a href="#health-faq">FAQs</a></nav>
   <section id="health-basics" className="health-introduction"><div><p className="health-eyebrow">UNDERSTAND YOUR PROTECTION</p><h2>Support for medical bills.<br />More breathing room for life.</h2></div><div><p>A hospital stay can affect more than your health. Health insurance helps meet eligible treatment costs, so an unexpected bill does not have to fall entirely on your savings.</p><p>The right starting point is your household: who needs cover, where you would seek care and what protection you already have. Then compare the benefits and conditions that matter to you.</p></div></section>
   <section id="health-plans" className="health-section"><p className="health-eyebrow">FIND YOUR FIT</p><h2>Different lives. Different cover needs.</h2><p className="health-section-lead">Start with the kind of protection you need, then compare the details of individual products.</p><div className="health-plan-grid">{plans.map(([title,copy],i)=><article key={title}><span className="health-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
   <section id="health-cover" className="health-section"><p className="health-eyebrow">LOOK BEYOND THE PREMIUM</p><h2>What may be covered &mdash; and what to check</h2><div className="health-cover-grid"><article><span className="health-icon green"><ShieldPlus aria-hidden="true" /></span><h3>Benefits to look for</h3><ul><li>Eligible in-patient hospitalisation and surgery expenses.</li><li>Covered day-care procedures that do not require an overnight stay.</li><li>Related tests and medicines before or after hospitalisation, within the policy's specified periods.</li><li>Optional benefits such as outpatient or maternity cover, where offered.</li></ul></article><article><span className="health-icon purple"><ClipboardCheck aria-hidden="true" /></span><h3>Conditions that matter</h3><ul><li>Benefits can have waiting periods, limits and eligibility requirements.</li><li>Excluded treatments and non-payable items remain your responsibility.</li><li>A larger sum insured does not remove co-payments or treatment caps.</li><li>Medical history must be disclosed accurately in the proposal.</li></ul></article></div></section>
   <section id="health-compare" className="health-section"><p className="health-eyebrow">YOUR COMPARISON CHECKLIST</p><h2>Six details worth a closer look</h2><div className="health-check-grid">{checklist.map(([title,copy])=><article key={title}><CheckCircle2 size={23} aria-hidden="true" /><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
   <section className="health-section health-steps"><p className="health-eyebrow">FROM QUESTIONS TO CLARITY</p><h2>Take the next step at your pace</h2><ol><li><strong>Tell us what you need</strong><p>Use the quotation form to request a conversation. Keep ages, existing cover and preferred hospitals handy.</p></li><li><strong>Review the options</strong><p>Compare benefits, costs and policy conditions. Ask about anything you do not understand.</p></li><li><strong>Apply when you are ready</strong><p>Complete the insurer's proposal and disclosures. Review the issued documents and cover start date.</p></li></ol></section>
   <section id="health-claims" className="health-section"><p className="health-eyebrow">WHEN YOU NEED TO USE YOUR COVER</p><h2>Two ways a hospital claim can work</h2><div className="health-cover-grid"><article><h3>Cashless treatment</h3><p>Contact the insurer or administrator and the hospital insurance desk. Share policy details and arrange the required authorisation. Approved costs are settled with the hospital; check which expenses you must pay yourself.</p></article><article><h3>Reimbursement</h3><p>Pay the hospital, retain your documents and submit the claim through the insurer's process within its required timelines. Payment depends on the expenses being admissible under your policy.</p></article></div><Link className="health-text-link" href="/claims">Explore claims assistance <ArrowRight size={18} aria-hidden="true" /></Link></section>
   <section id="health-faq" className="health-section health-faq"><p className="health-eyebrow">A LITTLE MORE CLARITY</p><h2>Your health insurance questions, answered</h2>{faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section>
   <section className="health-bottom-cta"><div><h2>Let&apos;s find a starting point for your cover.</h2><p>A few details are all you need to begin the conversation.</p></div><a href="#get-quotation">Request a health quote <ArrowRight size={18} aria-hidden="true" /></a></section>
   <p className="health-policy-note">Benefits, exclusions, acceptance and claims depend on the insurer and the specific policy. Read the Customer Information Sheet and full policy wording before buying. For consumer guidance, visit <a href="https://irdai.gov.in/health-dept" target="_blank" rel="noopener noreferrer">IRDAI&apos;s health insurance guidance</a>.</p>
  </div>
 </main>;
}
