"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {createPortal} from "react-dom";
import {usePathname} from "next/navigation";
import {ArrowRight,MessageCircle,X} from "lucide-react";
import {canonicalPath,resolveSeoRoute} from "@/lib/seo";
import {QuotationModal} from "./quotation-modal";
import "./insurance-assistance-modal.css";
const sessionKey='magikpolicy-assistance-shown';
export function assistanceAllowed(path:string){const source=resolveSeoRoute(path)?.source||path.replace(/\/$/,'')||'/';return !['/contact','/contact-us','/disclaimer','/desclaimer','/privacy-policy','/privacy','/terms','/terms-and-conditions','/terms-and-condition','/login'].includes(source)&&!/^\/(admin|partner|customer|auth)(\/|$)/.test(source);}
export function InsuranceAssistanceModal({close,onQuote,sourcePath}:{close:()=>void;onQuote:()=>void;sourcePath:string}){
 const dialog=useRef<HTMLDialogElement>(null);const [mobile,setMobile]=useState(''),[whatsapp,setWhatsapp]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[sent,setSent]=useState(false);
 useEffect(()=>{const node=dialog.current!;const previous=document.activeElement as HTMLElement|null;const overflow=document.body.style.overflow;document.body.style.overflow='hidden';node.showModal();return()=>{node.close();document.body.style.overflow=overflow;previous?.focus()}},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setError('');if(!/^[6-9]\d{9}$/.test(mobile)){setError('Enter a valid 10-digit Indian mobile number.');return}const website=new FormData(e.currentTarget).get('website');setBusy(true);try{const r=await fetch('/api/public/callback-requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mobile,whatsapp,sourcePath,consent:true,website})});const b=await r.json();if(!r.ok)throw Error(b.error||'Unable to request assistance.');setSent(true)}catch(e){setError(e instanceof Error?e.message:'Please try again.')}finally{setBusy(false)}}
 return createPortal(<dialog ref={dialog} className="insurance-assistance" aria-labelledby="assistance-title" onCancel={e=>{e.preventDefault();close()}} onClick={e=>{if(e.target===e.currentTarget){const r=e.currentTarget.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close()}}}><button className="assistance-close" aria-label="Close insurance assistance" onClick={close}><X/></button><div className="assistance-copy"><p className="assistance-eyebrow">DON?T IGNORE</p><h2 id="assistance-title">Your <span>Insurance!</span></h2><p className="assistance-intro">Your insurance is our priority. Get expert assistance with personalized plans that fit your needs.</p>{sent?<div role="status" className="assistance-success"><h3>Thank you!</h3><p>Our team will contact you to help with your insurance needs.</p><button className="mp-form-action" onClick={close}>Done</button></div>:<form onSubmit={submit} noValidate aria-busy={busy}><div className="assistance-fields"><label className="mp-input-group"><span className="mp-input-prefix">+91</span><input className="mp-control" aria-label="Mobile number" type="tel" inputMode="numeric" autoComplete="tel-national" placeholder="Mobile Number" maxLength={10} value={mobile} onChange={e=>setMobile(e.target.value.replace(/\D/g,'').slice(0,10))} required/></label><button className="mp-form-action" disabled={busy}>{busy?'Sending?':'Continue'}<ArrowRight size={22}/></button></div><p className="assistance-quote">Enter number for assistance, <button type="button" onClick={onQuote}>click here for quote</button></p><label className="assistance-whatsapp"><input className="mp-check" type="checkbox" checked={whatsapp} onChange={e=>setWhatsapp(e.target.checked)}/>Get updates on <MessageCircle color="#25b94b" size={23}/> WhatsApp</label><input name="website" tabIndex={-1} autoComplete="off" className="assistance-honeypot" aria-hidden="true"/><p className="assistance-consent">By continuing, you agree to be contacted about your insurance request.</p>{error&&<p className="mp-form-error" role="alert">{error}</p>}</form>}<a className="assistance-terms" href={canonicalPath('/terms')}>*T &amp; C apply</a></div><div className="assistance-art"><img src="/brand/magikpolicy-family-hero.png" alt="Family together"/></div></dialog>,document.body);
}
export function TimedInsuranceAssistance(){const path=usePathname();const [open,setOpen]=useState(false),[quote,setQuote]=useState(false);const shown=useRef(false);
 useEffect(()=>{setOpen(false);setQuote(false);if(!assistanceAllowed(path)||shown.current)return;try{if(sessionStorage.getItem(sessionKey))return}catch{}let timer:ReturnType<typeof setTimeout>;function display(){if(document.hidden||document.querySelector('dialog[open]')){timer=setTimeout(display,1000);return}shown.current=true;try{sessionStorage.setItem(sessionKey,'1')}catch{}setOpen(true)}timer=setTimeout(display,30000);return()=>clearTimeout(timer)},[path]);
 return <>{open&&<InsuranceAssistanceModal sourcePath={path} close={()=>setOpen(false)} onQuote={()=>{setOpen(false);setQuote(true)}}/>}{quote&&<QuotationModal productType="health" close={()=>setQuote(false)}/>}</>;
}
