import Image from "next/image";
import Link from "next/link";
import { ShieldCheck, Sprout, UsersRound, Umbrella, IndianRupee, ClipboardCheck, Headphones, ArrowRight, Heart } from "lucide-react";
import { WebsiteQuotation } from "./quotation-form";
import "./health-insurance-page.css";
import "./life-insurance-page.css";
const types=[['Term protection','Life cover for a defined period. Pure term plans generally do not provide a survival payout; check any return-of-premium option separately.'],['Endowment and money-back','Combine life protection with specified savings benefits. Compare payout dates and distinguish guaranteed amounts from non-guaranteed bonuses.'],['Unit-linked plans','Combine life cover with investment funds. Fund values can rise or fall; the policyholder bears investment risk. Review charges and exit conditions.'],['Whole-life cover','Designed for longer-term protection, up to the age or duration stated in the contract. Check premiums and the applicable benefit structure.'],['Child-focused plans','May combine protection with benefits timed around future goals. Check who is insured and what happens if that person dies.'],['Retirement and annuity options','Focus on later-life income. Compare payout choices, survivor benefits and access to your money before committing.']];
const faqs=[['How is life insurance different from health insurance?','Life insurance pays the benefits specified for death or other insured events. Health insurance generally helps with eligible medical expenses. One does not automatically replace the other.'],['Does every life plan give money back at maturity?','No. Pure protection plans generally pay only for the insured event. Savings and other plans may have survival benefits, according to their terms.'],['Are ULIP returns guaranteed?','Investment returns in unit-linked funds depend on market performance. Illustrated values are not promises. Review fund risks, charges and the separate insurance benefits.'],['How long do I need to pay premiums?','The premium payment term can differ from the duration of cover. Confirm the payment schedule, due dates and consequences of missing a payment before applying.'],['What should my nominee know?','Tell them where the policy is stored, how to contact the insurer and where to find the claim checklist. Keep nomination and contact details current through the insurer.'],['Does requesting a quotation activate cover?','No. The form requests a conversation with MagikPolicy. Cover begins according to the policy issued by the insurer after its application requirements are met.']];
export function LifeInsurancePage(){return <main className="health-page life-page"><div className="health-top"><nav className="health-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/products">Insurance products</Link><span>/</span><span aria-current="page">Life Insurance</span></nav><div className="health-hero-layout">
 <header className="health-hero life-hero"><div className="health-hero-copy"><p className="health-eyebrow">LIFE INSURANCE</p><h1>A Brighter<br />Tomorrow for<br /><span>the People You Love</span></h1><p className="health-lead">Plan today for the people who count on you. Explore life cover that supports your family's financial needs and the future you want to build.</p><div className="health-hero-benefits">{[[ShieldCheck,'Financial security','For those who depend on you','purple'],[Sprout,'Life-stage choices','For changing responsibilities','green'],[UsersRound,'Explore your options','Compare benefits and commitments','pink']].map(([Icon,title,copy,color])=>{const Symbol=Icon as typeof ShieldCheck;return <div key={String(title)}><span className={'health-icon '+color}><Symbol aria-hidden="true"/></span><h2>{String(title)}</h2><p>{String(copy)}</p></div>;})}</div></div><div className="health-family life-family"><div className="health-family-shape"/><p className="life-family-caption">Today<br />for their<br />tomorrow <Heart size={22} aria-hidden="true"/></p><Image src="/brand/magikpolicy-family-hero.png" alt="Parents embracing their daughter" width={1161} height={1354} priority sizes="(max-width:700px) 80vw, 30vw"/></div></header>
 <aside className="product-quotation-sidebar health-quote" aria-label="Request an insurance quote"><WebsiteQuotation/></aside></div></div>
 <section className="health-advantages life-advantages"><div className="health-container"><h2>Why choose MagikPolicy for life insurance?</h2><div className="health-advantage-grid">{[[Umbrella,'Explore plan types','Understand protection, savings and linked options.','blue'],[IndianRupee,'Compare the commitment','Consider premiums alongside the benefits.','green'],[ClipboardCheck,'Clear conversations','Ask about terms before making a decision.','pink'],[Headphones,'Helpful support','Get guidance for your next step.','orange']].map(([Icon,title,copy,color])=>{const Symbol=Icon as typeof Umbrella;return <article key={String(title)}><span className={'health-icon '+color}><Symbol aria-hidden="true"/></span><h3>{String(title)}</h3><p>{String(copy)}</p></article>;})}</div></div></section>
 <div className="health-container health-content"><nav className="health-jump-links" aria-label="Life insurance guide"><a href="#life-basics">The basics</a><a href="#life-types">Plan types</a><a href="#life-compare">Compare plans</a><a href="#life-riders">Riders</a><a href="#life-claims">Claims</a><a href="#life-faq">FAQs</a></nav>
 <section id="life-basics" className="health-introduction"><div><p className="health-eyebrow">PROTECTION WITH A PURPOSE</p><h2>Think about the life<br />you want them to keep living.</h2></div><div><p>Life insurance is a contract that provides specified benefits in exchange for premiums. A death benefit can help loved ones meet financial responsibilities when the insured person is no longer there.</p><p>Start with the practical picture: everyday expenses, outstanding loans, education goals and existing resources. Separate the need for family protection from any savings or investment goal.</p></div></section>
 <section id="life-types" className="health-section"><p className="health-eyebrow">CHOOSE BY PURPOSE</p><h2>Different plans meet different needs</h2><div className="health-plan-grid life-plan-grid">{types.map(([title,copy],i)=><article key={title}><span className="health-number">0{i+1}</span><h3>{title}</h3><p>{copy}</p></article>)}</div><Link className="health-text-link" href="/products/term-life-insurance">Explore term protection <ArrowRight size={18} aria-hidden="true"/></Link></section>
 <section id="life-compare" className="health-section"><p className="health-eyebrow">LOOK AT THE FULL COMMITMENT</p><h2>Six questions to ask before choosing</h2><div className="health-check-grid">{[['What needs protecting?','List dependants, debts and essential goals. Review existing policies and savings before deciding how much additional cover to explore.'],['For how long?','Consider when your financial responsibilities may reduce. Compare the cover duration with the premium payment term.'],['Can I sustain the premiums?','Look beyond the first payment. Choose a commitment you can review against your household budget over time.'],['Which benefits are guaranteed?','Read the personalised benefit illustration. Keep contractual guarantees separate from projections, bonuses and market-linked outcomes.'],['What if my plans change?','Check surrender, withdrawal, paid-up and revival conditions. Leaving early can affect benefits and the amount you receive.'],['What must I disclose?','Answer proposal questions accurately, including health, occupation, habits and existing insurance. Ask the insurer to clarify anything uncertain.']].map(([title,copy])=><article key={title}><ClipboardCheck size={23} aria-hidden="true"/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
 <section id="life-riders" className="health-section"><p className="health-eyebrow">ADDITIONAL COVER, SPECIFIC CONDITIONS</p><h2>Understand what a rider adds</h2><div className="health-cover-grid"><article><h3>Benefits to explore</h3><p>Depending on the product, riders may offer additional benefits for specified accidents, disability or critical illness, or waive future premiums after a qualifying event.</p></article><article><h3>Details to confirm</h3><p>Check the extra premium, definitions, exclusions, waiting or survival conditions and rider duration. A rider does not make every illness or event payable.</p></article></div></section>
 <section className="health-section health-steps"><p className="health-eyebrow">A THOUGHTFUL NEXT STEP</p><h2>From your first question to your policy</h2><ol><li><strong>Share your priorities</strong><p>Request a quotation conversation. Keep your age, financial responsibilities and existing cover details ready.</p></li><li><strong>Review the proposal</strong><p>Compare benefits and complete the insurer's disclosures and any medical or document requirements.</p></li><li><strong>Keep your family informed</strong><p>Check the issued policy, nomination, payment schedule and start date. Store the documents where they can be found.</p></li></ol></section>
 <section id="life-claims" className="health-section"><p className="health-eyebrow">HELP WHEN IT MATTERS</p><h2>Make the claim process easier to navigate</h2><div className="health-cover-grid"><article><h3>Contact the insurer</h3><p>The claimant should notify the insurer and request the relevant claim form and checklist. Requirements depend on the policy, benefit and circumstances.</p></article><article><h3>Gather the documents</h3><p>A death claim commonly requires policy details, a death certificate, claimant identification and bank details. Medical records or additional evidence may be requested. Keep copies and the claim reference.</p></article></div><Link className="health-text-link" href="/claims">Explore claims assistance <ArrowRight size={18} aria-hidden="true"/></Link></section>
 <section id="life-faq" className="health-section health-faq"><p className="health-eyebrow">CLARITY FOR YOUR DECISION</p><h2>Your life insurance questions, answered</h2>{faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section>
 <section className="health-bottom-cta"><div><h2>Start with the people who matter most.</h2><p>Tell us a little about yourself to begin the conversation.</p></div><a href="#get-quotation">Request a life quote <ArrowRight size={18} aria-hidden="true"/></a></section>
 <p className="health-policy-note">Benefits, eligibility, exclusions and claims depend on the insurer and policy terms. Review the policy wording and benefit illustration before buying. Investment risk in linked funds is borne by the policyholder. Consumer resources: <a href="https://irdai.gov.in/life-insurance-products" target="_blank" rel="noopener noreferrer">IRDAI life insurance information</a>.</p>
 </div></main>;}
