import Image from "next/image";
import Link from "next/link";
import {ShieldPlus, IndianRupee, Clock3, Users, ClipboardCheck, Settings, Zap, ArrowRight} from "lucide-react";
import {WebsiteQuotation} from "./quotation-form";
import "./health-insurance-page.css";
import "./motor-insurance-page.css";
const addons=[['Zero depreciation','Reduces depreciation deductions on eligible replaced parts. Deductibles, claim limits and excluded items can still apply.'],['Roadside assistance','Help such as towing or breakdown support, within the service limits and locations specified by the insurer.'],['Engine protection','May cover specified engine or gearbox damage that a standard policy excludes. Read the insured events and exclusions carefully.'],['Return to invoice','May enhance settlement for eligible theft or total-loss claims. Vehicle age, valuation and claim conditions vary.']];
const faqs=[['Does third-party insurance cover repairs to my vehicle?','No. It covers insured liability to other people. Own-damage cover is needed for eligible damage to your own vehicle.'],['What is IDV?','Insured Declared Value is the vehicle value used for insurance purposes, particularly for eligible theft or total-loss settlement. Compare quotations with the same IDV to understand price differences.'],['What does a no-claim bonus apply to?','An eligible no-claim bonus reduces the own-damage premium, not the third-party premium. Disclose your previous claims accurately and confirm the entitlement with the insurer.'],['Does zero depreciation mean I pay nothing for repairs?','No. This add-on addresses specified depreciation deductions. You may still pay deductibles, excluded consumables and other non-payable expenses.'],['Can I renew an expired policy?','Ask the insurer about its renewal requirements. Inspection may be needed, and cover is not automatically backdated to fill the gap. Check the new start date before using the vehicle.'],['Does this form buy or renew my policy?','No. It requests a callback from MagikPolicy. Insurance starts only as stated in the policy issued by the insurer after its requirements are met.']];
export function MotorInsurancePage(){return <main className="health-page motor-page">
 <section className="motor-top"><Image className="motor-backdrop" src="/brand/motor-coastal-hero.png" alt="Silver SUV on a scenic coastal road" fill priority sizes="100vw" /><div className="motor-wash" />
 <div className="motor-top-inner"><nav className="health-breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><Link href="/products">Insurance products</Link><span>/</span><span aria-current="page">Motor Insurance</span></nav>
 <div className="motor-hero-layout"><header className="motor-hero-copy"><p className="health-eyebrow">MOTOR INSURANCE</p><h1>Protect Your Vehicle.<br /><span>Drive Worry-Free.</span></h1><p className="motor-lead">Explore motor insurance for your car or bike. Compare the cover, understand the details and find a starting point for your next journey.</p><div className="motor-hero-benefits">{[[ShieldPlus,'Comprehensive cover','Own damage and third-party protection','blue'],[IndianRupee,'Third-party cover','Protection for insured liability','green'],[Clock3,'Renewal support','Plan ahead for continued cover','pink']].map(([Icon,title,copy,color])=>{const Symbol=Icon as typeof ShieldPlus;return <div key={String(title)}><span className={'health-icon '+color}><Symbol aria-hidden="true" /></span><h2>{String(title)}</h2><p>{String(copy)}</p></div>;})}</div></header>
 <aside className="product-quotation-sidebar motor-quote" aria-label="Request an insurance quote"><WebsiteQuotation /></aside></div></div></section>
 <section className="motor-advantages" aria-label="Explore motor insurance with MagikPolicy"><div>{[[Users,'Compare your options','Look at cover as well as cost','pink'],[ClipboardCheck,'Choose your cover','Third party, own damage or comprehensive','green'],[Settings,'Useful add-ons','Tailor eligible cover to your needs','orange'],[Zap,'A simple first step','Request a quote or renewal conversation','purple']].map(([Icon,title,copy,color])=>{const Symbol=Icon as typeof Users;return <article key={String(title)}><span className={'health-icon '+color}><Symbol aria-hidden="true" /></span><div><h2>{String(title)}</h2><p>{String(copy)}</p></div></article>;})}</div></section>
 <div className="health-container health-content"><nav className="health-jump-links" aria-label="Motor insurance guide"><a href="#motor-cover">Cover types</a><a href="#motor-addons">Add-ons</a><a href="#motor-compare">Compare plans</a><a href="#motor-renew">Renewal</a><a href="#motor-claims">Claims</a><a href="#motor-faq">FAQs</a></nav>
 <section className="health-introduction"><div><p className="health-eyebrow">COVER FOR THE ROAD AHEAD</p><h2>Your vehicle. Your journeys.<br />Your choice of protection.</h2></div><div><p>Motor insurance helps manage the financial impact of insured accidents, vehicle loss and liability to others. The protection you receive depends on the type of policy you choose.</p><p>Start with the vehicle you use, your existing policy and the repair costs you could manage yourself. Then look at the conditions behind each quotation.</p><div className="motor-category-links"><Link href="/products/car-insurance">Explore car insurance <ArrowRight size={16}/></Link><Link href="/products/bike-insurance">Explore bike insurance <ArrowRight size={16}/></Link></div></div></section>
 <section id="motor-cover" className="health-section"><p className="health-eyebrow">UNDERSTAND THE DIFFERENCE</p><h2>Choose the cover your vehicle needs</h2><div className="motor-cover-grid"><article><span className="health-number">01</span><h3>Third-party liability</h3><p>Protects against covered legal liability for injury, death or property damage to others. It does not pay for repairs to your own vehicle.</p></article><article><span className="health-number">02</span><h3>Standalone own damage</h3><p>Covers eligible damage or loss to your vehicle. It must be considered alongside valid third-party insurance, which it does not replace.</p></article><article><span className="health-number">03</span><h3>Comprehensive cover</h3><p>Combines third-party liability and own-damage protection. The name does not mean every event or repair expense is covered.</p></article></div></section>
 <section className="health-section"><h2>Know what is included before you need it</h2><div className="health-cover-grid"><article><h3>Own-damage benefits to check</h3><ul><li>Accidental damage to the insured vehicle.</li><li>Theft, fire and specified natural events.</li><li>Cashless repairs at eligible network garages.</li><li>Optional add-ons listed in the policy schedule.</li></ul></article><article><h3>Common limits and exclusions</h3><ul><li>Wear and tear and routine maintenance.</li><li>Mechanical or electrical breakdown unless specifically covered.</li><li>Use outside the policy's permitted purpose or conditions.</li><li>Deductibles, depreciation and other non-payable expenses.</li></ul></article></div></section>
 <section id="motor-addons" className="health-section"><p className="health-eyebrow">PERSONALISE YOUR PROTECTION</p><h2>Add-ons worth understanding</h2><p className="health-section-lead">Availability depends on the insurer, vehicle and base policy. Choose benefits for your circumstances, rather than adding every option.</p><div className="health-plan-grid">{addons.map(([title,copy])=><article key={title}><Settings size={25} color="#8648d8" aria-hidden="true"/><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
 <section id="motor-compare" className="health-section"><p className="health-eyebrow">COMPARE LIKE FOR LIKE</p><h2>A lower premium is only one part of the picture</h2><div className="health-check-grid">{[['Vehicle details','Use the correct registration, model, variant, fuel type and declared use in every quote.'],['Insured value','Check that the IDV and selected add-ons are comparable across the options you review.'],['Your contribution','Compare compulsory and voluntary deductibles. A lower price can come with a larger share of a claim.'],['Repair access','Check garages near your home or workplace and how cashless authorisation works.'],['Claim history','Confirm the no-claim bonus declared in your proposal matches your actual entitlement.'],['Policy dates','Own-damage and third-party cover may end on different dates. Check both before renewing.']].map(([title,copy])=><article key={title}><ClipboardCheck size={24} aria-hidden="true"/><div><h3>{title}</h3><p>{copy}</p></div></article>)}</div></section>
 <section id="motor-renew" className="health-section health-steps"><p className="health-eyebrow">KEEP YOUR NEXT JOURNEY IN MIND</p><h2>Make renewal a considered decision</h2><ol><li><strong>Keep the details ready</strong><p>Have your registration certificate, existing policy, expiry dates and previous claim details available.</p></li><li><strong>Review what has changed</strong><p>Check vehicle use, ownership, accessories and the protection you need. Confirm details with the insurer.</p></li><li><strong>Check the issued policy</strong><p>Verify the registration, cover dates, IDV, add-ons and payment receipt. Keep an accessible copy.</p></li></ol><Link className="health-text-link" href="/renew">Get renewal help <ArrowRight size={18}/></Link></section>
 <section id="motor-claims" className="health-section"><p className="health-eyebrow">WHEN SOMETHING GOES WRONG</p><h2>Start your claim with clear information</h2><div className="health-cover-grid"><article><h3>Report and document</h3><p>Prioritise safety, notify the insurer promptly and follow its instructions. Record the incident and retain relevant photographs and documents. Ask whether a police report, inspection or repair authorisation is needed.</p></article><article><h3>Understand the repair route</h3><p>With approved cashless repairs, the insurer settles eligible costs with the network garage. For reimbursement, retain bills and payment receipts for assessment. You remain responsible for costs the policy does not pay.</p></article></div><Link className="health-text-link" href="/claims">Explore claims assistance <ArrowRight size={18}/></Link></section>
 <section id="motor-faq" className="health-section health-faq"><p className="health-eyebrow">ANSWERS BEFORE YOU APPLY</p><h2>Motor insurance questions, explained</h2>{faqs.map(([question,answer])=><details key={question}><summary>{question}</summary><p>{answer}</p></details>)}</section>
 <section className="health-bottom-cta"><div><h2>Ready to talk about your vehicle cover?</h2><p>Share a few details and let us help you explore the next step.</p></div><a href="#get-quotation">Request a motor quote <ArrowRight size={18}/></a></section>
 <p className="health-policy-note">Cover, add-ons, exclusions and claim settlement depend on the insurer and policy wording. Review your schedule before buying or renewing. Read <a href="https://irdai.gov.in/web/policy-holder/motor-insurance" target="_blank" rel="noopener noreferrer">IRDAI's motor insurance guidance</a> for consumer information.</p>
 </div></main>;}
