"use client";
import { PartnerBusinessEmpty } from "@/components/partner/partner-business-empty";
import { PartnerSkeleton } from "@/components/partner/partner-skeleton";


import { useCallback, useEffect, useMemo, useState } from "react";
import { BarChart3, CalendarDays, ChevronDown, ChevronRight, Coins, FileText, Percent, Users, WalletCards } from "lucide-react";
import { supabaseAuth } from "@/lib/supabase-client";

type Data = any;
const money = new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 });
const dateLabel = (value: string) => value ? new Date(`${value}T00:00:00`).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" }) : "";

export function PartnerEarningsContent() {
  const [loading, setLoading] = useState(true);
  const [data, setData] = useState<Data | null>(null);
  const [tab, setTab] = useState<"direct" | "network">("direct");
  const [error, setError] = useState("");
  const load = useCallback(async () => {setLoading(true);setError("");try {
    const { data: auth } = await supabaseAuth.auth.getSession();
    const response = await fetch("/api/partner/earnings", { headers: { Authorization: `Bearer ${auth.session?.access_token || ""}` } });
    const body = await response.json();
    if (response.ok) setData(body); else setError(body.error || "Earnings could not be loaded.");
  } catch { setError("Unable to load earnings. Please refresh and try again."); } finally { setLoading(false); }}, []);
  useEffect(() => { void load(); }, [load]);
  const selected = data?.[tab] || { earnings: 0, policies: 0, businessValue: 0, averageRate: 0 };
  const maxTrend = useMemo(() => Math.max(1, ...(data?.trend || []).flatMap((item: any) => [item.businessValue, item.commission])), [data]);
  const products = tab === "direct" ? (data?.products || []) : [];
  const colors = ["pink", "blue", "red", "violet", "cyan", "gray"];

  if (loading) return <PartnerSkeleton view="earnings" />;
  if(!data||data.hasActivity===false)return <div className="pe-page"><div className="pe-heading"><h1>Earnings</h1></div>{error?<section className="pd-card" role="alert"><p>{error}</p><button type="button" onClick={()=>void load()}>Try again</button></section>:<PartnerBusinessEmpty kind="earnings"/>}</div>;
  return (
    <div className="pe-page">
      <div className="pe-heading">
        <div><p>Earnings</p><h1>{tab === "direct" ? "Your Earnings" : "Network Team Earnings"}</h1><span>Track commissions from your own business and your network team. Commission shown after adjustments and clawbacks.</span></div>
        <button className="pe-period"><CalendarDays /> {data ? `${dateLabel(data.period.start)} - ${dateLabel(data.period.end)}` : "Current month"}<ChevronDown /></button>
      </div>
      {error && <p className="pe-error">{error}</p>}
      <section className="pe-summary">
        {[
          ["Total Earnings", data?.summary.totalEarnings || 0, Coins, "violet"],
          ["My Earnings", data?.summary.myEarnings || 0, WalletCards, "blue"],
          ["Network Earnings", data?.summary.networkEarnings || 0, Users, "orange"],
          ["Total Business Value", data?.summary.totalBusinessValue || 0, FileText, "green"],
        ].map(([label, value, Icon, tone]: any) => <article key={label}><i className={tone}><Icon /></i><div><span>{label}</span><strong>{money.format(value)}</strong><small>Current period</small></div></article>)}
      </section>
      <div className="pe-tabs"><button className={tab === "direct" ? "active" : ""} onClick={() => setTab("direct")}>My Business</button><button className={tab === "network" ? "active" : ""} onClick={() => setTab("network")}>Network Team Business</button></div>
      <section className="pe-mobile-metrics">
        {[["Total Policies", selected.policies, FileText, "violet"], ["Business Value", money.format(selected.businessValue), BarChart3, "blue"], ["Your Commission", money.format(selected.earnings), Coins, "green"], ["Avg. Commission Rate", `${selected.averageRate.toFixed(1)}%`, Percent, "orange"]].map(([label,value,Icon,tone]:any)=><article key={label}><i className={tone}><Icon/></i><div><span>{label}</span><strong>{value}</strong><small>Current period</small></div></article>)}
      </section>
      <div className="pe-grid">
        <article className="pe-card pe-performance">
          <h2>{tab === "direct" ? "My Business Performance" : "Network Team Performance"}</h2><p>Commission earned from {tab === "direct" ? "policies sold by you" : "eligible business generated by your downline"}.</p>
          <div className="pe-performance-metrics"><span><FileText/><small>Total Policies</small><b>{selected.policies}</b></span><span><BarChart3/><small>Business Value</small><b>{money.format(selected.businessValue)}</b></span><span><Coins/><small>Your Commission</small><b>{money.format(selected.earnings)}</b></span></div>
          <h3>Product-wise Earnings</h3>
          {products.length ? <div className="pe-product-table"><div className="head"><span>Product</span><span>Policies</span><span>Business Value</span><span>Commission Rate</span><span>Commission</span></div>{products.map((item:any,index:number)=><div key={item.product}><span><i className={colors[index%colors.length]}>{item.product.slice(0,1)}</i><b>{item.product}</b></span><span>{item.policies}</span><span>{money.format(item.businessValue)}</span><span>{item.rate.toFixed(1)}%</span><strong>{money.format(item.commission)}</strong><ChevronRight/></div>)}</div> : <div className="pe-empty">{tab === "network" ? "Network earnings will appear here when your team generates eligible business." : "No earnings recorded for this period."}</div>}
          <div className="pe-recent-title"><h3>Recent Policies</h3><button>View All</button></div>
          <div className="pe-recent">{(data?.recentPolicies || []).map((item:any)=><div key={item.id}><b>{item.policyNumber}</b><span>{dateLabel(item.date)}</span><span><b>{item.customer}</b><small>{item.product}</small></span><strong>{money.format(item.commission)}<small>Commission</small></strong><ChevronRight/></div>)}{!data?.recentPolicies?.length && <div className="pe-empty">No recent policies.</div>}</div>
        </article>
        <aside className="pe-side">
          <article className="pe-card pe-trend"><div><h2>Business Trend</h2><button>Last 6 Months <ChevronDown/></button></div><div className="pe-legend"><span>Business Value</span><span>Commission</span></div><div className="pe-chart">{(data?.trend || []).map((item:any)=><div key={item.key}><section><i style={{height:`${Math.max(2,item.businessValue/maxTrend*150)}px`}}/><b style={{height:`${Math.max(2,item.commission/maxTrend*150)}px`}}/></section><span>{item.label}</span></div>)}</div></article>
          <article className="pe-card pe-mix"><h2>Product Mix (My Business)</h2><div><div className="pe-donut"><span><b>{money.format(data?.direct.earnings || 0)}</b>Total Earnings</span></div><ul>{(data?.products || []).slice(0,5).map((item:any,index:number)=><li key={item.product}><i className={colors[index%colors.length]}/><span>{item.product}</span><b>{data?.direct.earnings ? Math.round(item.commission/data.direct.earnings*100) : 0}%</b></li>)}</ul></div></article>
          <article className="pe-motivate">🏆 <span><b>Keep Going!</b><small>You’re doing great. Grow your business to unlock higher commission slabs.</small></span><ChevronRight/></article>
        </aside>
      </div>
    </div>
  );
}
