import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {PGlite} from '@electric-sql/pglite';
test('category edits preserve identity and active status, rollback mappings on failure, and protect slab references',async()=>{const db=new PGlite();try{await db.exec(`create role anon;create role authenticated;create role service_role;
create table categories(id uuid primary key default gen_random_uuid());create table product_types(id uuid primary key default gen_random_uuid(),category_id uuid references categories(id));create table insurers(id uuid primary key default gen_random_uuid());`);
await db.exec(readFileSync('supabase/migrations/202608270001_company_commission_categories.sql','utf8'));
await db.exec(readFileSync('supabase/migrations/202608270002_commission_category_company_mappings.sql','utf8'));
await db.exec(`alter table company_commission_categories add column name text;create table partner_commission_slabs(id uuid primary key default gen_random_uuid(),commission_category_id uuid references company_commission_categories(id) on delete restrict);insert into categories default values;insert into product_types(category_id) select id from categories;insert into product_types(category_id) select id from categories;insert into insurers default values;`);
await db.exec(readFileSync('supabase/migrations/202609160001_commission_category_edit.sql','utf8'));
const sector=(await db.query('select id from categories')).rows[0].id,types=(await db.query('select id from product_types')).rows,company=(await db.query('select id from insurers')).rows[0].id;
const details={name:'Original',categoryId:sector,productTypeId:types[0].id,high:[company],average:[],low:[]};
const save=(id,body)=>db.query('select save_commission_category_mapping($1,$2) result',[id,JSON.stringify(body)]);
const id=(await save(null,details)).rows[0].result.id;
await db.query('update company_commission_categories set active=false where id=$1',[id]);
assert.equal((await save(id,{...details,name:'Edited',productTypeId:types[1].id})).rows[0].result.id,id);
assert.equal((await db.query('select active from company_commission_categories')).rows[0].active,false);
await assert.rejects(save(null,{...details,productTypeId:types[1].id}),/unique/);
await assert.rejects(save(id,{...details,name:'Should roll back',high:['11111111-1111-4111-8111-111111111111']}),/foreign key/);
assert.equal((await db.query('select name from company_commission_categories')).rows[0].name,'Edited');assert.equal((await db.query('select insurer_id from commission_category_company_mappings')).rows[0].insurer_id,company);
await db.query('insert into partner_commission_slabs(commission_category_id) values($1)',[id]);await assert.rejects(db.query('delete from company_commission_categories where id=$1',[id]),/foreign key/);
await db.exec('delete from partner_commission_slabs');await db.query('delete from company_commission_categories where id=$1',[id]);assert.equal((await db.query('select * from commission_category_company_mappings')).rows.length,0);
assert.equal((await db.query("select has_function_privilege('authenticated','save_commission_category_mapping(uuid,jsonb)','execute') allowed")).rows[0].allowed,false);
}finally{await db.close()}});
