const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');const {PGlite}=require('@electric-sql/pglite');
test('lead activity migration preserves old data, audits statuses and keeps follow-up history atomically',async()=>{const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create table users(id text primary key);insert into users values ('admin');
 create table leads(id uuid primary key default gen_random_uuid(),status text default 'new',updated_at timestamptz default now());
 create table website_quote_requests(id uuid primary key default gen_random_uuid(),status text default 'new' constraint website_quote_requests_status_check check(status in ('new','contacted','converted','closed')),updated_at timestamptz default now());
 create table policies(id uuid primary key default gen_random_uuid());
 insert into website_quote_requests(status) values ('closed');insert into leads(status) values ('proposal');
 create function create_partner_lead_policy(p_user_id text,p_lead_id uuid,p_details jsonb) returns jsonb language plpgsql as $$begin update public.leads set status='converted' where id=p_lead_id;return '{}';end $$;`);
 await db.exec(fs.readFileSync('supabase/migrations/202609290001_lead_followups.sql','utf8'));
 assert.equal((await db.query('select status from website_quote_requests')).rows[0].status,'lost');
 const id=(await db.query('select id from leads')).rows[0].id;
 const action=(name,data)=>db.query('select manage_lead_activity($1,$2,$3,$4,$5) result',['internal',id,'admin',name,JSON.stringify(data)]);
 await assert.rejects(action('status',{status:'lost'}),/reason/);
 await assert.rejects(action('status',{status:'lost',lostReason:'Other',lostNote:' '}),/reason/);
 await action('status',{status:'qualified'});await action('status',{status:'qualified'});
 assert.equal((await db.query('select * from lead_status_history')).rows.length,1);
 const requestId='11111111-1111-4111-8111-111111111111';const data={requestId,scheduledAt:'2099-10-02T11:00:00+05:30',followupType:'call',note:'Discuss quote'};
 const first=(await action('schedule',data)).rows[0].result.id;assert.equal((await action('schedule',data)).rows[0].result.id,first);
 await assert.rejects(action('reschedule',{...data,requestId:'22222222-2222-4222-8222-222222222222',followupId:first,followupType:'bad'}),/check constraint/);
 assert.equal((await db.query('select status from lead_followups where id=$1',[first])).rows[0].status,'scheduled');
 const second=(await action('reschedule',{...data,requestId:'22222222-2222-4222-8222-222222222222',followupId:first})).rows[0].result.id;
 await action('complete',{followupId:second});assert.equal((await db.query('select count(*)::int n from lead_followups')).rows[0].n,2);
 await assert.rejects(action('complete',{followupId:second}),/already/);
 await action('status',{status:'lost',lostReason:'Other',lostNote:'Changed plans'});
 assert.equal((await db.query('select lost_by from leads')).rows[0].lost_by,'admin');
 await assert.rejects(action('schedule',{...data,requestId:'33333333-3333-4333-8333-333333333333'}),/Closed/);
 await db.query('select create_partner_lead_policy($1,$2,$3)',['admin',id,'{}']);
 const converted=(await db.query('select * from leads')).rows[0];assert.equal(converted.converted_by,'admin');assert.ok(converted.converted_at);
 assert.equal((await db.query('select count(*)::int n from lead_followups')).rows[0].n,2);
 }finally{await db.close()}});
