const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:n=>imports[n]||require(n)});return exports;}
const customer=load('src/lib/customers/schema.ts'),partner=load('src/lib/partners/schema.ts'),quote=load('src/lib/quote-request.ts');
test('customer mobile accepts exactly ten national digits and stored +91 values',()=>{for(const mobile of ['9876543210','+919876543210'])assert.equal(customer.customerSyncSchema.parse({mobile}).mobile,'+919876543210');for(const mobile of ['987654321','98765432101','+9198765432101','abc9876543210','+123456789012345'])assert.equal(customer.customerSyncSchema.safeParse({mobile}).success,false,mobile)});
test('partner mobile does not normalize alphabetic input into a valid number',()=>{const base={fullName:'Test Partner',email:'test@example.com'};for(const mobile of ['987654321','98765432101','abc9876543210'])assert.equal(partner.partnerInputSchema.safeParse({...base,mobile}).success,false,mobile)});
test('quote mobile rejects excess national digits and preserves country-code compatibility',()=>{const base={customerName:'Test Customer',productType:'health'};for(const mobile of ['987654321','98765432101','+9198765432101'])assert.equal(quote.quoteRequestSchema.safeParse({...base,mobile}).success,false);assert.equal(quote.quoteRequestSchema.parse({...base,mobile:'+91 98765 43210'}).mobile,'9876543210')});
test('every dedicated mobile input has a ten-digit maximum and exact-length pattern',()=>{
 let checked=0;
 function walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const path=dir+'/'+entry.name;if(entry.isDirectory())walk(path);else if(path.endsWith('.tsx')){const source=ts.createSourceFile(path,fs.readFileSync(path,'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TSX);function visit(node){if(ts.isJsxSelfClosingElement(node)&&node.tagName.getText(source)==='input'){const attrs=node.attributes.properties.filter(ts.isJsxAttribute);const attr=name=>attrs.find(a=>a.name.getText(source)===name)?.initializer;const text=name=>attr(name)?.getText(source)||'';if(/"(?:mobile|contact|whatsappNumber)"/.test(text('name'))||text('type')==='"tel"'||/\{(?:mobile|invitePhone)/.test(text('value'))||text('inputMode')==='"tel"'||/mobile number/i.test(text('placeholder'))&&!/search/i.test(text('placeholder'))){checked++;assert.equal(text('maxLength'),'{10}',path);assert.equal(text('pattern'),'"[0-9]{10}"',path);assert.ok(attr('onInput'),path);}}ts.forEachChild(node,visit)}visit(source)}}}walk('src');assert.ok(checked>=13);
});
