import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {PGlite} from '@electric-sql/pglite';
test('lead conversion saves the policy atomically and retains approval safeguards',async()=>{const db=new PGlite();try{
await db.exec(`create role anon;create role authenticated;create role service_role;
create table users(id text primary key,status text);create table agents(id uuid primary key default gen_random_uuid(),user_id text,status text);
create table leads(id uuid primary key default gen_random_uuid(),agent_id uuid,name text,contact text,status text);
create table customers(id uuid primary key default gen_random_uuid(),agent_id uuid,name text,contact text,created_from_lead_id uuid,customer_code text not null unique,created_at timestamptz default now());
create table categories(id uuid primary key default gen_random_uuid(),active boolean);create table product_types(id uuid primary key default gen_random_uuid(),category_id uuid,active boolean);create table insurers(id uuid primary key default gen_random_uuid(),active boolean);
create table policies(id uuid primary key default gen_random_uuid(),policy_number text unique,customer_id uuid,agent_id uuid,category_id uuid,product_type_id uuid,insurer_id uuid,premium numeric,coverage numeric,start_date date,expiry_date date,business_type text,status text);
create table policy_status_history(policy_id uuid,from_status text,to_status text,changed_by text);
insert into users values('owner','active'),('other','active');insert into agents(user_id,status) values('owner','active'),('other','active');insert into categories(active) values(true);insert into product_types(category_id,active) select id,true from categories;insert into insurers(active) values(true);
insert into leads(agent_id,name,contact,status) select id,'Test Customer','9876543210','converted' from agents where user_id='owner';`);
await db.exec(readFileSync('supabase/migrations/202609140001_partner_lead_policy.sql','utf8'));
await db.exec(`alter table policies add column product_id uuid;alter table policies add column plan_id uuid;alter table policies add column tenure_months integer;alter table policies add column updated_at timestamptz;
create table products(id uuid primary key,category_id uuid);create table plans(id uuid primary key,product_id uuid,insurer_id uuid);`);
await db.exec(readFileSync('supabase/migrations/202609140002_partner_policy_review.sql','utf8'));
await db.exec(`alter table leads add column updated_at timestamptz;create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);`);
await db.exec(readFileSync('supabase/migrations/202609150001_partner_customer_lead_journey.sql','utf8'));
await db.exec("update leads set status='new'");
const lead=(await db.query('select id from leads')).rows[0].id;const sector=(await db.query('select id from categories')).rows[0].id;const type=(await db.query('select id from product_types')).rows[0].id;const insurer=(await db.query('select id from insurers')).rows[0].id;
const details={policyNumber:'POL-001',sectorId:sector,productTypeId:type,insurerId:insurer,premium:1500,coverage:100000,startDate:'2026-09-14',tenureMonths:12,businessType:'fresh'};
const create=(user='owner',body=details,id=lead)=>db.query('select create_partner_lead_policy($1,$2,$3) as policy',[user,id,JSON.stringify(body)]);
await assert.rejects(create('other'),/your leads/);await assert.rejects(create('owner',{...details,tenureMonths:0}),/valid policy details/);assert.equal((await db.query('select count(*)::int n from customers')).rows[0].n,0);
await db.query("insert into customers(agent_id,name,contact,customer_code) select id,'Existing Customer','9999999999','EXISTING001' from agents where user_id='owner'");
const customer=(await db.query("select id from customers where customer_code='EXISTING001'")).rows[0].id;
await db.query('update leads set customer_id=$1 where id=$2',[customer,lead]);
const first=(await create()).rows[0].policy;assert.equal(first.customer_id,customer);assert.equal(first.status,'pending');assert.equal((await db.query('select status from leads where id=$1',[lead])).rows[0].status,'converted');assert.equal(first.source_lead_id,lead);assert.equal((await db.query('select customer_code from customers')).rows[0].customer_code,'EXISTING001');
assert.equal((await create()).rows[0].policy.id,first.id);assert.equal((await db.query('select count(*)::int n from policies')).rows[0].n,1);
await db.exec("insert into leads(agent_id,name,contact,status) select id,'Second Customer','9876543211','converted' from agents where user_id='owner'");const second=(await db.query('select id from leads where contact=$1',['9876543211'])).rows[0].id;
await assert.rejects(create('owner',details,second),/unique/);assert.equal((await db.query('select count(*)::int n from customers')).rows[0].n,1);
await db.exec("update leads set status='new' where contact='9876543211'");

assert.equal(first.review_status,'pending');assert.equal(first.tenure_months,12);assert.equal(first.expiry_date,'2027-09-13');
await assert.rejects(db.query("update policies set status='issued' where id=$1",[first.id]),/policies_require_review/);
const review=(decision,note='',expected='pending')=>db.query('select review_partner_policy($1,$2,$3,$4,$5) as policy',[first.id,'other',decision,note,expected]);
await assert.rejects(review('rejected'),/reason/);
await review('hold','Please verify the insurer');
await assert.rejects(review('approved'),/changed/);
await review('approved','Verified','hold');
assert.equal((await db.query('select status from policies where id=$1',[first.id])).rows[0].status,'issued');
assert.equal((await db.query('select count(*)::int n from policy_review_history')).rows[0].n,2);
await assert.rejects(review('rejected','No','approved'),/already been reviewed/);
await db.exec("update leads set status='converted' where contact='9876543211'");
await assert.rejects(create('owner',{...details,policyNumber:'POL-002',productId:'11111111-1111-4111-8111-111111111111'},second),/product in this sector/);
const secondPolicy=(await create('owner',{...details,policyNumber:'POL-002'},second)).rows[0].policy;
await db.query('select review_partner_policy($1,$2,$3,$4,$5)',[secondPolicy.id,'other','rejected','Incorrect details','pending']);
assert.equal((await db.query('select status from policies where id=$1',[secondPolicy.id])).rows[0].status,'cancelled');
await assert.rejects(db.query("update policies set status='active' where id=$1",[secondPolicy.id]),/policies_require_review/);
assert.equal((await db.query("select has_function_privilege('authenticated','review_partner_policy(uuid,text,text,text,text)','execute') allowed")).rows[0].allowed,false);
assert.equal((await db.query("select has_function_privilege('authenticated','create_partner_lead_policy(text,uuid,jsonb)','execute') allowed")).rows[0].allowed,false);
}finally{await db.close()}});
