const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:n=>{if(!(n in imports))throw Error(n);return imports[n]},Date,Intl,Map,Number});return exports;}
const calc=load('src/lib/partners/dashboard.ts');const now=new Date('2026-01-01T00:00:00Z');
test('empty partner has zero totals, empty categories and six real calendar months',()=>{const r=calc.summarizeDashboard([],[],[],[],now);assert.equal(r.policiesSold,0);assert.equal(r.totalEarnings,0);assert.equal(r.categories.length,0);assert.equal(r.trend.length,6);assert.equal(r.trend[0].key,'2025-08');assert.equal(r.trend[5].key,'2026-01');});
test('sold policies exclude proposals/cancellations; renewals and Indian month boundaries are accurate',()=>{const policies=['active','issued','expired','proposal','cancelled'].map((status,i)=>({id:String(i),status,premium:'100.25',created_at:'2025-12-31T20:00:00Z',expiry_date:'2026-01-20',category:i===0?[{name:'Health'}]:{name:'Motor'}}));const r=calc.summarizeDashboard(policies,[],[],[],now);assert.equal(r.policiesSold,3);assert.equal(r.premium,300.75);assert.equal(r.renewalsDue,2);assert.equal(r.trend[5].policies,3);assert.equal(r.categories.reduce((s,c)=>s+c.count,0),3);assert.ok(Math.abs(r.categories.reduce((s,c)=>s+c.percentage,0)-100)<.001);});
test('net earnings include adjustments/clawbacks, paid and unpaid statuses, and negative results',()=>{const rows=[{id:'a',amount:'100.10',status:'paid',created_at:'2025-12-31T20:00:00Z',generation_level:0},{id:'b',amount:'20.20',status:'pending',created_at:'2025-12-01T00:00:00Z',generation_level:1}];const r=calc.summarizeDashboard([],rows,[{earning_id:'a',amount_delta:'10.05'},{earning_id:'other',amount_delta:9999}],[{earning_id:'a',amount:'5.15'},{earning_id:'b',amount:'30.20'}],now);assert.equal(r.totalEarnings,95);assert.equal(r.paidEarnings,105);assert.equal(r.unpaidEarnings,-10);assert.equal(r.trend[5].earnings,105);assert.equal(r.trend[4].earnings,-10);});
test('pagination retrieves records beyond the Supabase page cap and propagates failures',async()=>{const source=Array.from({length:1001},(_,id)=>({id}));const rows=await calc.dashboardRows(async(a,b)=>({data:source.slice(a,b+1),error:null}));assert.equal(rows.length,1001);await assert.rejects(calc.dashboardRows(async()=>({data:null,error:{message:'offline'}})),/load dashboard/);});
function endpoint(identity,fail=false){const calls=[];const db={from:table=>{const filters=[];let count=false;const q={select:(_s,o)=>{count=!!o?.head;return q},eq:(k,v)=>{filters.push([k,v]);return q},order:()=>q,limit:()=>q,range:()=>q,maybeSingle:async()=>{calls.push({table,filters});return {data:{id:'agent-one'},error:null}},then:(resolve,reject)=>{calls.push({table,filters});return Promise.resolve({data:[],count:count?0:null,error:fail?{message:'database down'}:null}).then(resolve,reject)}};return q}};const api=load('src/app/api/partner/dashboard/route.ts',{'next/server':{NextResponse:{json:(body,options)=>({body,...options})}},'@/lib/auth-server':{verifyRequestToken:async()=>identity},'@/lib/supabase-server':{supabaseServer:()=>db},'@/lib/partners/dashboard':calc});return {api,calls};}
const req={headers:{get:()=> 'Bearer token'},nextUrl:new URL('https://site.test/api/partner/dashboard?agent_id=another-agent')};
test('anonymous and non-partner users cannot query dashboard records',async()=>{for(const identity of [null,{uid:'user',role:'customer'},{uid:'user',role:'super_admin'}]){const s=endpoint(identity);assert.equal((await s.api.GET(req)).status,403);assert.equal(s.calls.length,0)}});
test('all dashboard reads use the verified partner, ignoring client-supplied agent IDs',async()=>{const s=endpoint({uid:'user-one',role:'partner'}),r=await s.api.GET(req);assert.equal(r.body.data.leads,0);assert.equal(r.headers['Cache-Control'],'private, no-store');assert.equal(s.calls[0].filters[0][1],'user-one');for(const call of s.calls.slice(1)){assert.ok(call.filters.some(([key,value])=>(key==='agent_id'||key==='earning.agent_id')&&value==='agent-one'),call.table)}});
test('database failures return an error instead of plausible zero metrics',async()=>{const s=endpoint({uid:'user',role:'partner'},true),r=await s.api.GET(req);assert.equal(r.status,500);assert.equal(r.body.data,undefined)});

test('welcome is based on record activity, including draft policies and zero-net earnings',()=>{const empty={leads:0,customers:0,quotes:0,policies:0,earnings:0};assert.equal(calc.hasPartnerActivity(empty),false);for(const kind of Object.keys(empty))assert.equal(calc.hasPartnerActivity({...empty,[kind]:1}),true,kind);});
