const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');
function load(file,imports={}){const exports={};vm.runInNewContext(ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020}}).outputText,{exports,require:n=>imports[n]});return exports;}
const htmlHelpers=load('src/lib/product-html.ts',{'sanitize-html':{default:require('sanitize-html')}});
const {productSchema,publicationErrors}=load('src/lib/product-catalog.ts',{zod:require('zod'),'./product-html':htmlHelpers}),{pdfSuggestions}=load('src/lib/product-pdf.ts');
test('publication requires reviewed content and valid catalog input',()=>{assert.ok(publicationErrors({name:'Incomplete'}).includes('Exclusions'));assert.equal(productSchema.safeParse({status:'published'}).success,false);const ready={name:'Health',slug:'health',template:'health',insurer_id:'a',product_type_id:'b',content:{overview:'Overview',benefits:'Benefits',exclusions:'Exclusions',seoDescription:'Description'}};assert.equal(publicationErrors(ready).length,0)});
test('PDF suggestions preserve source wording and page references without filling unknown fields',()=>{const s=pdfSuggestions([{page:2,text:'Key benefits\nCover subject to a limit.\nExclusions\nExcluded condition.'}]);assert.equal(s.benefits.text,'Cover subject to a limit.');assert.equal(s.benefits.pages[0],2);assert.equal(s.exclusions.text,'Excluded condition.');assert.equal(s.eligibility,undefined)});
function pdf(){const content='BT /F1 16 Tf 50 750 Td (Key benefits) Tj 0 -25 Td (Hospital cover with stated limits.) Tj ET';const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',`<< /Length ${content.length} >>\nstream\n${content}\nendstream`];let text='%PDF-1.4\n',offsets=[0];objects.forEach((o,i)=>{offsets.push(Buffer.byteLength(text));text+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=Buffer.byteLength(text);text+=`xref\n0 6\n0000000000 65535 f \n`+offsets.slice(1).map(n=>String(n).padStart(10,'0')+' 00000 n \n').join('')+`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new Uint8Array(Buffer.from(text));}
test('PDF parser extracts a real PDF with page numbering',async()=>{const {PDFParse}=require('pdf-parse');const parser=new PDFParse({data:pdf()});try{const result=await parser.getText();assert.equal(result.pages[0].num,1);assert.match(result.text,/Hospital cover with stated limits/);}finally{await parser.destroy()}});

test('catalog mutations require edit permission and publication cannot bypass review',async()=>{
 const {NextRequest,NextResponse}=require('next/server');
 const row={id:'11111111-1111-4111-8111-111111111111',name:'Health',slug:'health',template:'health',insurer_id:'i',product_type_id:'t',content:{overview:'Text',benefits:'Text',exclusions:'Text',seoDescription:'Text'}};
 let writes=0;const route=allowed=>load('src/app/api/admin/products/route.ts',{'next/server':{NextRequest,NextResponse},zod:require('zod'),'@/lib/product-catalog':{productSchema,publicationErrors},'@/lib/auth-server':{verifyRequestToken:async()=>({uid:'actor'})},'@/lib/rbac':{ensureAdminPermission:async()=>allowed},'@/lib/supabase-server':{supabaseServer:()=>({from:()=>({select:()=>({eq:()=>({single:async()=>({data:row})})}),update:()=>{writes++;throw Error('unexpected write')}})})}});
 const request=body=>new NextRequest('https://site.test/api/admin/products',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
 const body={id:row.id,status:'published',expectedUpdatedAt:'2026-09-16',reviewed:false};
 assert.equal((await route(false).PATCH(request(body))).status,403);assert.equal((await route(true).PATCH(request(body))).status,400);assert.equal(writes,0);
});
