const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript'),path=require('node:path');
const cache={};function load(file){if(cache[file])return cache[file];const exports={};const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,esModuleInterop:true}}).outputText;vm.runInNewContext(code,{exports,URL,Buffer,TextDecoder,setTimeout,clearTimeout,require:n=>n.startsWith('.')?load(path.join(path.dirname(file),n)+'.ts'):require(n)});return cache[file]=exports;}
const html=load('src/lib/product-html.ts'),extract=load('src/lib/product-website-import.ts'),remote=load('src/lib/product-url-fetch.ts');
test('HTML formatting survives while scripts, event handlers, embeds and unsafe URLs are removed',()=>{const clean=html.safeProductHtml('<p onclick="alert(1)">Cover <strong>details</strong></p><script>alert(1)</script><iframe src="https://bad.test"></iframe><a href="javascript:alert(1)">bad</a><table><tr><td>Limit</td></tr></table>');assert.match(clean,/<strong>details<\/strong>/);assert.match(clean,/<table>/);assert.doesNotMatch(clean,/onclick|script|iframe|javascript:/);assert.equal(html.cleanProductContent({overview:'<script>bad()</script><p>Good</p>',_format_overview:'html'}).overview,'<p>Good</p>');});
test('website extraction identifies sections, keeps tables and resolves brochure links',()=>{const result=extract.extractProductWebsite('<html><title>Health cover</title><body><nav><h2>Benefits</h2><p>Menu</p></nav><main><h1>Health Plus</h1><p>Overview copy</p><h2>Key Benefits</h2><ul><li>Hospital cover</li></ul><h2>Exclusions</h2><p>Excluded treatment</p><h2>Waiting periods</h2><table><tr><td>30 days</td></tr></table><a href="/brochure.pdf">Brochure</a></main></body></html>','https://insurer.example/product');assert.equal(result.title,'Health Plus');assert.match(result.sections.find(s=>s.key==='benefits').html,/Hospital cover/);assert.doesNotMatch(JSON.stringify(result.sections),/Menu/);assert.match(result.sections.find(s=>s.key==='waitingPeriods').html,/<table>/);assert.equal(result.pdfs[0].url,'https://insurer.example/brochure.pdf');assert.equal(result.sections.some(s=>s.key==='copay'),false)});
test('website importer rejects credentials, local domains, IP literals and non-web schemes',()=>{for(const url of ['file:///etc/passwd','http://127.0.0.1','http://2130706433','https://[::1]','https://localhost','http://metadata.internal','https://user:pass@example.com','https://example.com:8080'])assert.throws(()=>remote.publicWebsiteUrl(url));assert.equal(remote.publicWebsiteUrl('https://example.com/product#features').href,'https://example.com/product');});
test('resolved private, mapped, reserved and link-local addresses cannot be fetched',()=>{for(const ip of ['127.0.0.1','10.0.0.1','172.16.0.1','192.168.1.1','169.254.169.254','0.0.0.0','100.64.0.1','::1','fc00::1','fe80::1','::ffff:127.0.0.1','224.0.0.1'])assert.equal(remote.isPublicAddress(ip),false,ip);assert.equal(remote.isPublicAddress('8.8.8.8'),true);assert.equal(remote.isPublicAddress('2606:4700:4700::1111'),true);});

test('whole-page formatting is saved safely and legacy fields combine without duplication',()=>{
 const source='<h2 style="color:#ff0000;text-align:center">Cover</h2><p><span style="font-size:24px;background-color:rgb(255, 255, 0)">Benefits</span><sup>2</sup></p><img src="https://example.com/cover.png" alt="Cover" onerror="bad()"><div style="position:fixed;background-image:url(javascript:bad())">Details</div>';
 const clean=html.cleanProductContent({pageHtml:source}).pageHtml;
 assert.match(clean,/color:#ff0000/);assert.match(clean,/font-size:24px/);assert.match(clean,/<sup>2<\/sup>/);assert.match(clean,/<img src="https:/);assert.doesNotMatch(clean,/onerror|position|background-image|javascript/);
 const fields=[['overview','Overview'],['benefits','Benefits']];
 assert.equal(html.productPageHtml({overview:'Original',benefits:'<p>Rich</p>',_format_benefits:'html'},fields),'<h2>Overview</h2><p>Original</p><h2>Benefits</h2><p>Rich</p>');
 assert.equal(html.productPageHtml({pageHtml:'',overview:'Old copy'},fields),'');
 assert.equal(html.productPageHtml({pageHtml:clean,overview:'Old copy'},fields),clean);
});
