const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),ts=require('typescript');const {chromium}=require('@playwright/test');
const compile=file=>ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2020,jsx:ts.JsxEmit.React}}).outputText;
const htmlHelpers={exports:{}};vm.runInNewContext(compile('src/lib/product-html.ts'),{exports:htmlHelpers.exports,require:()=>({default:require('sanitize-html')})});
const fields={exports:{}};vm.runInNewContext(compile('src/lib/product-catalog.ts'),{exports:fields.exports,require:n=>n==='zod'?require('zod'):htmlHelpers.exports});
test('admin can create a draft, preview it and must confirm review before publishing',async()=>{const browser=await chromium.launch();try{const page=await browser.newPage();page.setDefaultTimeout(8000);page.on("pageerror",e=>console.log("Browser error:",e.message));await page.setContent('<div id="root"></div>');await page.addScriptTag({path:'node_modules/react/umd/react.development.js'});await page.addScriptTag({path:'node_modules/react-dom/umd/react-dom.development.js'});
await page.evaluate(({definitions,validation})=>{const product_html_1={plainProductText:value=>value.replace(/<[^>]*>/g,'').trim()};window.modules={'next/link':{default:props=>React.createElement('a',props)},'next/navigation':{useRouter:()=>({replace:path=>window.replaced=path,push:path=>window.pushed=path})},'@/components/admin/product-html-editor':{ProductHtmlEditor:()=>null},'@/components/admin/product-website-import':{ProductWebsiteImport:()=>null},'@/lib/product-html':{safeProductHtml:value=>value,textToProductHtml:value=>value,productPageHtml:content=>content.pageHtml||Object.values(content).join('')},react:window.React,'@/lib/supabase-client':{accessToken:async()=>''},'@/lib/product-catalog':{...definitions,productSchema:{safeParse:()=>({success:true})},productValidationMessages:()=>[],publicationErrors:eval('('+validation+')')}};window.calls=[];window.row=null;window.fetch=async(url,init={})=>{if(init.method==='POST'){const input=JSON.parse(init.body);window.calls.push(input);window.row={id:'11111111-1111-4111-8111-111111111111',name:input.name,category_id:input.categoryId,product_type_id:input.productTypeId,insurer_id:input.insurerId,slug:input.slug,template:input.template,content:input.content,plans:[],updated_at:'2026-09-16',publication_status:'draft'};return{ok:true,json:async()=>({id:window.row.id})};}return{ok:true,json:async()=>({data:window.row?[window.row]:[],sectors:[{id:'s',name:'Health'}],types:[{id:'t',name:'Family Floater',category_id:'s'}],insurers:[{id:'i',name:'Insurer'}]})}};}, {definitions:{categoryFields:fields.exports.categoryFields,commonFields:fields.exports.commonFields},validation:fields.exports.publicationErrors.toString()});
for(const [file,name] of [['src/components/catalog/product-view.tsx','@/components/catalog/product-view'],['src/components/admin/product-manager.tsx','manager'],['src/components/admin/product-list.tsx','list']]){await page.addScriptTag({content:`{const exports={};const require=n=>n.endsWith('.css')?{}:window.modules[n];${compile(file)};window.modules[${JSON.stringify(name)}]=exports;}`});}
await page.evaluate(()=>{window.root=ReactDOM.createRoot(document.getElementById('root'));window.root.render(React.createElement(window.modules.manager.ProductManager));});
await page.getByLabel('Product name',{exact:true}).fill('Health Plus');await page.getByLabel('Category',{exact:true}).selectOption('s');await page.getByLabel('Product type',{exact:true}).selectOption('t');await page.getByLabel('Insurer',{exact:true}).selectOption('i');await page.getByRole('button',{name:'Generate from name'}).click();await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).first().waitFor();assert.equal(await page.evaluate(()=>window.calls[0].slug),'health-plus');await page.getByRole('button',{name:'5. Preview & publish'}).click();await page.getByRole('button',{name:'Publish reviewed product'}).click();await page.locator('.catalog-toast').filter({hasText:'Required: Page content'}).waitFor();await page.locator('.catalog-toast').filter({hasText:'SEO description'}).waitFor();await page.getByRole('heading',{name:'Health Plus',exact:true}).waitFor();
assert.equal(await page.evaluate(()=>window.replaced),'/admin/products/11111111-1111-4111-8111-111111111111/edit');
await page.evaluate(()=>window.root.render(React.createElement(window.modules.manager.ProductManager,{key:'edit',productId:window.row.id})));
await page.getByRole('heading',{name:'Edit Product',exact:true}).waitFor();await page.waitForFunction(()=>document.querySelector('input')?.value==='Health Plus');
assert.equal(await page.getByLabel('Product name',{exact:true}).inputValue(),'Health Plus');
await page.getByLabel('Product name',{exact:true}).fill('Health Updated');await page.getByRole('button',{name:'5. Preview & publish'}).click();await page.getByRole('button',{name:'Publish reviewed product'}).click();await page.locator('.catalog-toast').filter({hasText:'Unsaved changes'}).waitFor();await page.getByRole('button',{name:'Save draft',exact:true}).click();await page.getByRole('status').filter({hasText:'Draft saved'}).first().waitFor();assert.equal(await page.evaluate(()=>window.calls[1].id),'11111111-1111-4111-8111-111111111111');
await page.evaluate(()=>window.root.render(React.createElement(window.modules.list.ProductList)));
await page.getByRole('heading',{name:'Health Updated',exact:true}).waitFor();assert.equal(await page.getByRole('link',{name:'Add Product',exact:true}).getAttribute('href'),'/admin/products/new');assert.equal(await page.getByRole('link',{name:'Edit / Review'}).getAttribute('href'),'/admin/products/11111111-1111-4111-8111-111111111111/edit');assert.equal(await page.getByLabel('Product name',{exact:true}).count(),0);
await page.evaluate(()=>window.root.render(React.createElement(window.modules.manager.ProductManager,{key:'missing',productId:'missing'})));await page.getByRole('alert').filter({hasText:'Product not found'}).first().waitFor();assert.equal(await page.getByRole('button',{name:'Save draft',exact:true}).count(),0);

}finally{await browser.close()}});

