import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {PGlite} from '@electric-sql/pglite';
test('product catalog extends existing records, preserves plan IDs and rolls back invalid changes',async()=>{const db=new PGlite();try{
 await db.exec(`create role anon;create role authenticated;create role service_role;
 create table users(id text primary key,status text);create table agents(id uuid primary key default gen_random_uuid(),user_id text,status text);
 create table categories(id uuid primary key default gen_random_uuid(),name text,active boolean default true);
 create table product_types(id uuid primary key default gen_random_uuid(),category_id uuid,active boolean default true);
 create table insurers(id uuid primary key default gen_random_uuid(),name text,active boolean default true);
 create table products(id uuid primary key default gen_random_uuid(),category_id uuid not null references categories(id),name text not null);
 create table plans(id uuid primary key default gen_random_uuid(),product_id uuid references products(id),insurer_id uuid references insurers(id),name text,base_premium_rules jsonb default '{}');
 create table product_documents(id uuid primary key default gen_random_uuid(),product_id uuid references products(id),file_url text);
 create table leads(id uuid primary key,customer_id uuid,agent_id uuid,status text,name text,contact text,updated_at timestamptz);
 create table customers(id uuid primary key,agent_id uuid,name text,contact text,created_from_lead_id uuid,customer_code text,created_at timestamptz);
 create table policies(id uuid primary key,product_id uuid,source_lead_id uuid,policy_number text,customer_id uuid,agent_id uuid,category_id uuid,product_type_id uuid,insurer_id uuid,premium numeric,coverage numeric,start_date date,expiry_date date,business_type text,status text,plan_id uuid,tenure_months integer,review_status text,policy_document_path text);
 create table policy_status_history(policy_id uuid,from_status text,to_status text,changed_by text);
 create schema storage;create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 insert into users values('admin','active');insert into categories(name) values('Health'),('Motor');insert into insurers(name) values('Insurer');insert into product_types(category_id) select id from categories;
 insert into products(category_id,name) select id,'Legacy' from categories where name='Health';`);
 await db.exec(readFileSync('supabase/migrations/202609160002_product_catalog.sql','utf8'));
 const legacy=(await db.query('select * from products')).rows[0];assert.equal(legacy.catalog_managed,false);
 const sector=(await db.query("select id from categories where name='Health'")).rows[0].id,type=(await db.query('select id from product_types where category_id=$1',[sector])).rows[0].id,insurer=(await db.query('select id from insurers')).rows[0].id;
 const input={name:'Health Plus',categoryId:sector,productTypeId:type,insurerId:insurer,slug:'health-plus',productCode:'UIN',template:'health',status:'review',content:{overview:'Overview'},plans:[{name:'Base',description:'Base benefits'}]};
 const save=(id,body)=>db.query('select save_catalog_product($1,$2,$3) id',[id,'admin',JSON.stringify(body)]);
 const id=(await save(legacy.id,input)).rows[0].id;assert.equal(id,legacy.id);const plan=(await db.query('select * from plans')).rows[0];assert.equal(plan.product_id,id);
 await save(id,{...input,name:'Updated',plans:[{id:plan.id,name:'Base updated',description:'New details'}]});assert.equal((await db.query('select id from plans')).rows[0].id,plan.id);
 await assert.rejects(save(id,{...input,name:'Should rollback',plans:[{id:'11111111-1111-4111-8111-111111111111',name:'Wrong',description:''}]}),/does not belong/);assert.equal((await db.query('select name from products')).rows[0].name,'Updated');assert.equal((await db.query('select catalog_active from plans')).rows[0].catalog_active,true);
 await save(id,{...input,plans:[]});assert.equal((await db.query('select catalog_active from plans')).rows[0].catalog_active,false);
 await assert.rejects(save(null,input),/unique/);assert.equal((await db.query('select count(*)::int n from products')).rows[0].n,1);
 assert.equal((await db.query("select has_function_privilege('authenticated','save_catalog_product(uuid,text,jsonb)','execute') allowed")).rows[0].allowed,false);
 }finally{await db.close()}});
