"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { accessToken } from "@/lib/supabase-client";

type RequestRow = { id:string;name:string;whatsapp_number:string;claim_amount:number;claim_failure_reason:string;location:string;status:string;created_at:string;policyUrl:string|null;failureUrl:string|null };
async function api(init:RequestInit={}){const token=await accessToken();return fetch("/api/admin/claim-help",{...init,headers:{...(init.headers??{}),Authorization:`Bearer ${token}`}})}

export function ClaimHelpDirectory(){
  const[rows,setRows]=useState<RequestRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[active,setActive]=useState<RequestRow|null>(null);
  const load=useCallback(async()=>{setLoading(true);const response=await api(),body=await response.json();response.ok?setRows(body.data):setError(body.error);setLoading(false)},[]);
  useEffect(()=>{const timer=setTimeout(load,250);return()=>clearTimeout(timer)},[load]);
  const visible=useMemo(()=>rows.filter(row=>`${row.name} ${row.whatsapp_number} ${row.location}`.toLowerCase().includes(query.toLowerCase())),[rows,query]);
  async function status(row:RequestRow,next:string){const response=await api({method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:row.id,status:next})});if(!response.ok)return setError((await response.json()).error);await load()}
  return <div className="partner-directory claim-help-directory"><header className="directory-heading"><div><h1>Claim Help Requests</h1><p>Review failed-claim assistance requests and attached documents.</p></div></header>{error&&<p className="form-error">{error}</p>}<section className="directory-card"><div className="directory-toolbar"><strong>{rows.length} requests</strong><div className="directory-search"><input className="mp-control" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search name, WhatsApp or location…"/></div></div><div className="directory-table-wrap"><table className="directory-table claim-help-table"><thead><tr><th>Customer</th><th>Claim Amount</th><th>Location</th><th>Submitted</th><th>Status</th><th>Action</th></tr></thead><tbody>{loading?<tr><td colSpan={6}>Loading requests…</td></tr>:visible.length===0?<tr><td colSpan={6}>No claim help requests found.</td></tr>:visible.map(row=><tr key={row.id}><td><div className="directory-person"><span>{row.name.slice(0,2).toUpperCase()}</span><div><strong>{row.name}</strong><small>WhatsApp: {row.whatsapp_number}</small></div></div></td><td><strong>{new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0}).format(row.claim_amount)}</strong></td><td>{row.location}</td><td>{new Date(row.created_at).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}</td><td><select className={(`lead-status ${row.status}`) + " mp-control"} value={row.status} onChange={e=>status(row,e.target.value)}><option value="new">New</option><option value="reviewing">Reviewing</option><option value="contacted">Contacted</option><option value="resolved">Resolved</option><option value="closed">Closed</option></select></td><td><button className="secondary-button" onClick={()=>setActive(row)}>View details</button></td></tr>)}</tbody></table></div></section>{active&&<div className="directory-modal" onMouseDown={()=>setActive(null)}><section onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setActive(null)}>×</button><h2>{active.name}</h2><div className="view-summary"><span>WhatsApp<strong>{active.whatsapp_number}</strong></span><span>Claim amount<strong>{new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR"}).format(active.claim_amount)}</strong></span><span>Location<strong>{active.location}</strong></span><span>Status<strong>{active.status}</strong></span></div><div className="claim-reason"><small>Reason for claim failure</small><p>{active.claim_failure_reason}</p></div><div className="modal-buttons"><a className="secondary-button" href={active.policyUrl??"#"} target="_blank" rel="noreferrer">View Policy</a><a className="secondary-button" href={active.failureUrl??"#"} target="_blank" rel="noreferrer">View Failure Document</a></div></section></div>}</div>
}
