"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {accessToken} from "@/lib/supabase-client";
import "./record-actions.css";
export function CustomerCreate({partners,close,saved}:{partners:any[];close:()=>void;saved:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');const options=partners.filter(p=>['active','approved'].includes(p.status));
 useEffect(()=>{const node=ref.current!;const previous=document.activeElement as HTMLElement|null;node.showModal();return()=>{node.close();previous?.focus()}},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const values=Object.fromEntries(new FormData(e.currentTarget));setBusy(true);setError('');try{const r=await fetch('/api/admin/customers',{method:'POST',headers:{Authorization:`Bearer ${await accessToken()}`,'Content-Type':'application/json'},body:JSON.stringify(values)});const b=await r.json();if(!r.ok)throw Error(b.error);saved()}catch(e){setError(e instanceof Error?e.message:'Unable to create customer.')}finally{setBusy(false)}}
 return <dialog ref={ref} className="record-action-dialog" aria-labelledby="customer-create-title" onCancel={e=>{e.preventDefault();if(!busy)close()}}><h2 id="customer-create-title">Add Customer</h2><form onSubmit={submit}><label className="mp-label">Customer name *<input className="mp-control" name="name" required minLength={2} maxLength={100} disabled={busy}/></label><label className="mp-label">Mobile number *<input className="mp-control" name="contact" type="tel" inputMode="numeric" required pattern="[6-9][0-9]{9}" minLength={10} maxLength={10} disabled={busy} onInput={e=>{e.currentTarget.value=e.currentTarget.value.replace(/\D/g,'').slice(0,10)}}/></label><label className="mp-label">Email<input className="mp-control" name="email" type="email" maxLength={254} disabled={busy}/></label><label className="mp-label">Address<textarea className="mp-control" name="address" maxLength={1000} disabled={busy}/></label><label className="mp-label">Assign partner *<select className="mp-control" name="agentId" required defaultValue="" disabled={busy}><option value="" disabled>Select partner</option>{options.map(p=><option key={p.id} value={p.id}>{(Array.isArray(p.users)?p.users[0]:p.users)?.full_name||'Partner'} ? {p.agent_code}</option>)}</select></label>{!options.length&&<p>No active or approved partners are available.</p>}{error&&<p role="alert" className="mp-form-error">{error}</p>}<footer><button type="button" disabled={busy} onClick={close}>Cancel</button><button className="primary-button" disabled={busy||!options.length}>{busy?'Saving?':'Save Customer'}</button></footer></form></dialog>;
}
