"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {accessToken} from "@/lib/supabase-client";
export function PolicyReview({policy,close,saved}:{policy:any;close:()=>void;saved:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[decision,setDecision]=useState("approved"),[note,setNote]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
 const editable=["pending","hold"].includes(policy.review_status);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();return()=>previous?.focus()},[]);
 async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{const response=await fetch("/api/admin/policies/review",{method:"POST",headers:{Authorization:`Bearer ${await accessToken()}`,"Content-Type":"application/json"},body:JSON.stringify({id:policy.id,decision,note,expectedStatus:policy.review_status})});const body=await response.json();if(!response.ok)throw Error(body.error);saved()}catch(error){setError(error instanceof Error?error.message:"Unable to review policy")}finally{setBusy(false)}}
 return <dialog ref={ref} className="admin-modal ap-review" aria-labelledby="policy-review-title" onCancel={e=>{e.preventDefault();if(!busy)close()}}><header><h2 id="policy-review-title">Review Partner Policy</h2><button type="button" disabled={busy} onClick={close} aria-label="Close review">?</button></header><p>{policy.policy_number} ? Review: {policy.review_status}</p><dl className="admin-form-grid">{Object.entries({Customer:policy.customer?.name,Mobile:policy.customer?.contact,Partner:policy.agent?.users?.full_name,"Partner code":policy.agent?.agent_code,Sector:policy.sector?.name,Type:policy.productType?.name,Product:policy.product?.name,Insurer:policy.insurer?.name,Plan:policy.plan?.name,Premium:policy.premium,Coverage:policy.coverage,"Start date":policy.start_date,"Expiry date":policy.expiry_date,"Tenure (months)":policy.tenure_months,"Business type":policy.business_type}).map(([label,value])=><div key={label}><dt>{label}</dt><dd>{String(value??"Not specified")}</dd></div>)}</dl>{policy.review_note&&<p>Previous review note: {policy.review_note}</p>}{error&&<p role="alert" className="form-error">{error}</p>}{editable&&<form onSubmit={submit}><fieldset disabled={busy}><label className="admin-form-field">Decision<select value={decision} onChange={e=>setDecision(e.target.value)}><option value="approved">Approve</option><option value="hold">Hold</option><option value="rejected">Reject</option></select></label><label className="admin-form-field">Review note {decision!=="approved"&&"(required)"}<textarea value={note} onChange={e=>setNote(e.target.value)} maxLength={2000} required={decision!=="approved"}/></label><p>{decision==="approved"?"Approval marks this policy as issued.":decision==="hold"?"The policy stays pending until reviewed again.":"Rejection marks this policy as cancelled."} The partner can see your decision and note.</p></fieldset><footer><button type="button" className="secondary-button" disabled={busy} onClick={close}>Cancel</button><button className="primary-button" disabled={busy}>{busy?"Saving?":"Save decision"}</button></footer></form>}</dialog>
}
