"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { PolicyFields } from "@/components/policy/policy-fields";
import { PolicyReview } from "@/components/admin/policy-review";
import Link from "next/link";
import { CalendarDays, ChevronLeft, ChevronRight, Download, FilePlus2, FileText, Filter, MoreVertical, Percent, Plus, Search, ShieldCheck, Upload, WalletCards } from "lucide-react";
import { accessToken } from "@/lib/supabase-client";

type Policy = any; type Options = { customers:any[];agents:any[];sectors:any[];products:any[];productTypes:any[];insurers:any[];plans:any[] }; type Metrics = {total:number;active:number;expiring:number;lapsed:number;cancelled:number;premium:number;commission:number};
const money = new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
const date = (value:string) => new Date(`${value}T00:00:00`).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});
async function request(init:RequestInit={}){const token=await accessToken();return fetch("/api/admin/policies",{...init,headers:{...(init.headers||{}),Authorization:`Bearer ${token||""}`}})}
const emptyOptions:Options={customers:[],agents:[],sectors:[],products:[],productTypes:[],insurers:[],plans:[]};

export function PoliciesDirectory(){
  const [review,setReview]=useState<Policy|null>(null),[rows,setRows]=useState<Policy[]>([]),[metrics,setMetrics]=useState<Metrics|null>(null),[options,setOptions]=useState<Options>(emptyOptions),[loading,setLoading]=useState(true),[error,setError]=useState(""),[query,setQuery]=useState(""),[category,setCategory]=useState(""),[insurer,setInsurer]=useState(""),[status,setStatus]=useState(""),[agent,setAgent]=useState(""),[customer,setCustomer]=useState(""),[tab,setTab]=useState("all"),[page,setPage]=useState(1),[pageSize,setPageSize]=useState(10),[open,setOpen]=useState(false),[saving,setSaving]=useState(false),[conversion,setConversion]=useState<any>(null);
  const load=useCallback(async()=>{setLoading(true);const response=await request(),body=await response.json();if(response.ok){setRows(body.data||[]);setMetrics(body.metrics);setOptions(body.options||emptyOptions);setError("")}else setError(body.error||"Policies could not be loaded.");setLoading(false)},[]);
  useEffect(()=>{const timer=setTimeout(()=>void load(),150);return()=>clearTimeout(timer)},[load]);
  useEffect(()=>{if(!location.search.includes("convert=1"))return;const saved=sessionStorage.getItem("policyLeadConversion");if(!saved)return;try{const value=JSON.parse(saved);setConversion(value);setOpen(true)}finally{sessionStorage.removeItem("policyLeadConversion")}},[]);
  const now=new Date(),soon=new Date();soon.setDate(now.getDate()+30);
  const classified=(row:Policy)=>{const expiry=new Date(`${row.expiry_date}T23:59:59`);if(row.status==="cancelled")return"cancelled";if(row.status==="expired"||(["active","issued"].includes(row.status)&&expiry<now))return"lapsed";if(["active","issued"].includes(row.status)&&expiry<=soon)return"expiring";return row.status};
  const categories=options.sectors;
  const filtered=useMemo(()=>rows.filter(row=>{const term=query.trim().toLowerCase(),kind=classified(row);return(!term||[row.policy_number,row.customer?.name,row.customer?.contact,row.agent?.users?.full_name,row.agent?.agent_code,row.product?.name,row.insurer?.name].join(" ").toLowerCase().includes(term))&&(!category||(row.sector?.id||row.product?.category?.id)===category)&&(!insurer||row.insurer_id===insurer)&&(!status||row.status===status)&&(!agent||row.agent_id===agent)&&(!customer||row.customer_id===customer)&&(tab==="all"||(tab==="review"?!!row.review_status:kind===tab))}),[rows,query,category,insurer,status,agent,customer,tab]);
  useEffect(()=>setPage(1),[query,category,insurer,status,agent,customer,tab,pageSize]);
  const pages=Math.max(1,Math.ceil(filtered.length/pageSize)),visible=filtered.slice((page-1)*pageSize,page*pageSize);
  async function create(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaving(true);setError("");const response=await request({method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))}),body=await response.json();setSaving(false);if(!response.ok)return setError(body.error||"Policy could not be created.");setOpen(false);setConversion(null);await load()}
  async function changeStatus(id:string,next:string){const response=await request({method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status:next})});if(!response.ok)setError((await response.json()).error||"Status could not be updated.");else await load()}
  function exportCsv(){const csv=[["Policy No.","Customer","Product","Insurer","Agent","Start","Expiry","Premium","Commission","Status"],...filtered.map(row=>[row.policy_number,row.customer?.name||"",row.product?.name||"",row.insurer?.name||"",row.agent?.users?.full_name||"",row.start_date,row.expiry_date,row.premium,row.commission,row.status])].map(line=>line.map(value=>`"${String(value).replaceAll('"','""')}"`).join(",")).join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv"})),anchor=document.createElement("a");anchor.href=url;anchor.download="magikpolicy-policies.csv";anchor.click();URL.revokeObjectURL(url)}
  const clear=()=>{setQuery("");setCategory("");setInsurer("");setStatus("");setAgent("");setCustomer("");setTab("all")};
  const cards=metrics?[["Total Policies",metrics.total,FileText,"violet"],["Active Policies",metrics.active,ShieldCheck,"green"],["Expiring Soon",metrics.expiring,CalendarDays,"orange"],["Lapsed Policies",metrics.lapsed,FilePlus2,"pink"],["Total Premium",money.format(metrics.premium),WalletCards,"blue"],["Total Commission",money.format(metrics.commission),Percent,"rose"]]:[];

  return <div className="ap-page">
    <header className="ap-heading"><div><p className="admin-eyebrow">Policy Management</p><h1>Policies</h1><span>View, manage and track all insurance policies across customers and agents. Update status, track renewals and commissions.</span></div><div><button className="secondary-button" title="CSV import template"><Upload/> Import Policies</button><button className="primary-button" onClick={()=>setOpen(true)}><Plus/> Add New Policy</button></div></header>
    {error&&<p className="form-error">{error}</p>}
    <section className="ap-metrics">{cards.map(([label,value,Icon,tone]:any)=><article key={label}><i className={tone}><Icon/></i><div><span>{label}</span><strong>{value}</strong><small>{label==="Expiring Soon"?"in next 30 days":"Database total"}</small></div></article>)}</section>
    <section className="ap-filters"><label className="wide mp-label"><span>Search</span><div className="mp-input-group"><Search/><input className="mp-control" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search by policy no., customer, agent..."/></div></label><label className="mp-label"><span>Product Sector</span><select className="mp-control" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All Sectors</option>{categories.map((item:any)=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="mp-label"><span>Insurance Company</span><select className="mp-control" value={insurer} onChange={e=>setInsurer(e.target.value)}><option value="">All Companies</option>{options.insurers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="mp-label"><span>Policy Status</span><select className="mp-control" value={status} onChange={e=>setStatus(e.target.value)}><option value="">All Status</option>{["proposal","pending","issued","active","expired","cancelled"].map(item=><option key={item}>{item}</option>)}</select></label><label className="mp-label"><span>Agent / Partner</span><select className="mp-control" value={agent} onChange={e=>setAgent(e.target.value)}><option value="">All Agents</option>{options.agents.map(item=><option key={item.id} value={item.id}>{item.users?.full_name||item.agent_code}</option>)}</select></label><label className="mp-label"><span>Customer</span><select className="mp-control" value={customer} onChange={e=>setCustomer(e.target.value)}><option value="">All Customers</option>{options.customers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><button className="ap-more"><Filter/> More Filters</button><button className="ap-reset" onClick={clear}>Reset</button></section>
    <section className="ap-list"><header><div className="ap-tabs">{[["all","All Policies",metrics?.total],["review","Partner Submissions",rows.filter(row=>row.review_status).length],["active","Active",metrics?.active],["expiring","Expiring Soon",metrics?.expiring],["lapsed","Lapsed",metrics?.lapsed],["cancelled","Cancelled",metrics?.cancelled]].map(item=><button className={tab===item[0]?"active":""} key={item[0] as string} onClick={()=>setTab(item[0] as string)}>{item[1]} ({item[2]||0})</button>)}</div><button className="secondary-button" onClick={exportCsv}><Download/> Export</button></header>
      <div className="ap-table-wrap"><table><thead><tr><th>Policy No.</th><th>Customer</th><th>Product</th><th>Company</th><th>Agent / Partner</th><th>Policy Dates</th><th>Premium</th><th>Commission</th><th>Status</th><th>Renewal</th><th>Actions</th></tr></thead><tbody>{loading?<tr><td colSpan={11}>Loading policies…</td></tr>:!visible.length?<tr><td colSpan={11}>No policies match the selected filters.</td></tr>:visible.map(row=>{const kind=classified(row),days=Math.ceil((new Date(`${row.expiry_date}T23:59:59`).getTime()-now.getTime())/86400000);return <tr key={row.id}><td><strong>{row.policy_number}</strong></td><td><div className="ap-person"><i>{(row.customer?.name||"CU").slice(0,2).toUpperCase()}</i><span><b>{row.customer?.name||"Customer"}</b><small>{row.customer?.contact||row.customer?.email||"—"}</small></span></div></td><td><b>{row.product?.name||"—"}</b></td><td>{row.insurer?.name||"—"}</td><td><div className="ap-person"><i>{(row.agent?.users?.full_name||"AG").slice(0,2).toUpperCase()}</i><span><b>{row.agent?.users?.full_name||"Agent"}</b><small>{row.agent?.agent_code}</small></span></div></td><td><span>{date(row.start_date)}</span><small>{date(row.expiry_date)}</small></td><td>{money.format(row.premium)}</td><td>{money.format(row.commission)}</td><td><select disabled={!!row.review_status&&row.review_status!=="approved"} className={(`ap-status ${kind}`) + " mp-control"} value={row.status} onChange={e=>changeStatus(row.id,e.target.value)}>{["proposal","pending","issued","active","expired","cancelled"].map(item=><option key={item}>{item}</option>)}</select>{row.review_status&&<small>Review: {row.review_status}</small>}</td><td><span className={`ap-renewal ${kind}`}>{kind==="expiring"?`${days} days`:kind==="lapsed"?"Expired":"Not Due"}</span></td><td>{row.review_status&&<button className="secondary-button" onClick={()=>setReview(row)}>Review</button>}<Link className="ap-action" href={`/admin/policies/${row.id}/edit`} aria-label={`Edit ${row.policy_number}`}><MoreVertical/></Link></td></tr>})}</tbody></table></div>
      <footer><span>Showing {filtered.length?(page-1)*pageSize+1:0} to {Math.min(page*pageSize,filtered.length)} of {filtered.length} policies</span><div><select className="mp-control" value={pageSize} onChange={e=>setPageSize(Number(e.target.value))}><option value="10">10 per page</option><option value="25">25 per page</option><option value="50">50 per page</option></select><button disabled={page===1} onClick={()=>setPage(page-1)}><ChevronLeft/></button>{Array.from({length:Math.min(5,pages)},(_,i)=>Math.min(Math.max(1,page-2)+i,pages)).filter((v,i,a)=>a.indexOf(v)===i).map(value=><button className={page===value?"active":""} key={value} onClick={()=>setPage(value)}>{value}</button>)}<button disabled={page===pages} onClick={()=>setPage(page+1)}><ChevronRight/></button></div></footer>
    </section>
    {review&&<PolicyReview policy={review} close={()=>setReview(null)} saved={()=>{setReview(null);void load()}}/>}
    {open&&<div className="admin-modal-backdrop" onMouseDown={()=>setOpen(false)}><form className="admin-modal ap-form" onSubmit={create} onMouseDown={e=>e.stopPropagation()}><header><div><p className="admin-eyebrow">Policy Management</p><h2>Add New Policy</h2></div><button type="button" onClick={()=>setOpen(false)}>×</button></header><PolicyFields options={options} conversion={conversion}/><footer><button type="button" className="secondary-button" onClick={()=>setOpen(false)}>Cancel</button><button className="primary-button" disabled={saving}>{saving?"Saving…":"Create Policy"}</button></footer></form></div>}
  </div>
}
