"use client";
import {useState,type FormEvent} from "react";
import {accessToken} from "@/lib/supabase-client";
import {safeProductHtml} from "@/lib/product-html";
type Result={title:string;sections:Array<{label:string;html:string}>;sourceUrl:string;importedAt:string;warning:string;pdfs:Array<{title:string;url:string}>};
export function ProductWebsiteImport({onApply,onError}:{onError?:(message:string)=>void;onApply:(html:string,source:string,date:string,replace:boolean)=>void}){
 const[url,setUrl]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState<Result|null>(null),[replace,setReplace]=useState(false),[applied,setApplied]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setResult(null);setApplied(false);setReplace(false);try{const r=await fetch('/api/admin/products/import-url',{method:'POST',headers:{Authorization:`Bearer ${await accessToken()}`,'content-type':'application/json'},body:JSON.stringify({url})});const b=await r.json();if(!r.ok)throw Error(b.error);setResult(b);}catch(e){const message=e instanceof Error?e.message:'Unable to import website';setError(message);onError?.(message)}finally{setBusy(false)}}
 const html=result?safeProductHtml(result.sections.map(s=>'<h2>'+s.label+'</h2>'+s.html).join('')):'';
 return <section className="product-url-import"><h2>Import from website</h2><p>Import details into your page editor, then edit the whole page freely.</p><form className="mp-form" onInvalid={e=>onError?.((e.target as HTMLInputElement).validationMessage)} onSubmit={submit}><label className="mp-label">Product website URL<input className="mp-control" type="url" value={url} onChange={e=>setUrl(e.target.value)} required maxLength={2000}/></label><button className="mp-form-action" disabled={busy}>{busy?'Reading website...':'Extract product information'}</button></form>{error&&<p role="alert">{error}</p>}{result&&<><p>{result.warning}</p><a href={result.sourceUrl} target="_blank" rel="noreferrer">View source</a><details><summary>Preview imported content</summary><div className="product-rich-content" dangerouslySetInnerHTML={{__html:html}}/></details><label className="mp-label"><input type="checkbox" className="mp-check" checked={replace} disabled={applied} onChange={e=>setReplace(e.target.checked)}/>Replace existing page content (otherwise append)</label><button type="button" disabled={applied||!html} onClick={()=>{onApply(html,result.sourceUrl,result.importedAt,replace);setApplied(true)}}>{applied?'Added to editor':replace?'Replace page content':'Append to page editor'}</button>{result.pdfs.length>0&&<ul>{result.pdfs.map(p=><li key={p.url}><a href={p.url} target="_blank" rel="noreferrer">{p.title}</a></li>)}</ul>}</>}</section>;
}
