"use client";
import {useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {Pencil,Trash2} from "lucide-react";
import {recordModules} from "@/lib/admin-records";
import {accessToken} from "@/lib/supabase-client";
import "./record-actions.css";
export function RecordActions({module,row,onChanged,onEdit}:{module:string;row:any;onChanged:()=>void;onEdit?:()=>void}){
 const [mode,setMode]=useState<'edit'|'delete'|null>(null),[values,setValues]=useState<Record<string,string>>({}),[busy,setBusy]=useState(false),[error,setError]=useState('');const dialog=useRef<HTMLDialogElement>(null);const config=recordModules[module];
 useEffect(()=>{if(!mode)return;const trigger=document.activeElement as HTMLElement;const node=dialog.current!;node.showModal();return()=>{node.close();trigger?.focus()}},[mode]);
 function open(next:'edit'|'delete'){setError('');setValues(Object.fromEntries(config.fields.map(f=>[f.key,String(row[f.key]??'')])));setMode(next)}
 async function submit(){if(busy)return;setBusy(true);setError('');try{const r=await fetch(`/api/admin/records/${module}/${row.id}`,{method:mode==='delete'?'DELETE':'PATCH',headers:{Authorization:`Bearer ${await accessToken()}`,'Content-Type':'application/json'},...(mode==='edit'?{body:JSON.stringify(values)}:{})});const b=await r.json();if(!r.ok)throw Error(b.error);setMode(null);onChanged()}catch(e){setError(e instanceof Error?e.message:'Action failed')}finally{setBusy(false)}}
 return <span className="record-actions">{config.fields.length>0&&<button type="button" aria-label="Edit record" title="Edit" onClick={()=>onEdit?onEdit():open('edit')}><Pencil size={17}/></button>}<button type="button" disabled={module==='policies'&&row.status!=='cancelled'} aria-label="Delete record" title={module==='policies'&&row.status!=='cancelled'?'Only cancelled policies can be deleted':'Delete'} onClick={()=>open('delete')}><Trash2 size={17}/></button>{mode&&createPortal(<dialog className="record-action-dialog" ref={dialog} aria-labelledby="record-action-title" onCancel={e=>{e.preventDefault();if(!busy)setMode(null)}}><h2 id="record-action-title">{mode==='delete'?'Delete record':'Edit record'}</h2><form onSubmit={e=>{e.preventDefault();submit()}}>{mode==='delete'?<p>Delete {row.name||row.customer_name||row.policy_number||row.agent_code||'this record'} permanently? Related notes and record history may also be removed. This cannot be undone. Sign-in accounts and uploaded files are retained.</p>:config.fields.map(f=><label className="mp-label" key={f.key}>{f.label}{f.required?' *':''}{f.type==='select'?<select className="mp-control" disabled={busy} value={values[f.key]} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}>{f.options!.map(o=><option key={o}>{o}</option>)}</select>:f.type==='textarea'?<textarea className="mp-control" disabled={busy} required={f.required} maxLength={f.max} value={values[f.key]} onChange={e=>setValues(v=>({...v,[f.key]:e.target.value}))}/>:<input className="mp-control" disabled={busy} type={f.type||'text'} required={f.required} maxLength={f.type==='tel'?10:f.max} min={f.type==='number'?0:undefined} step={f.type==='number'?'0.01':undefined} value={values[f.key]} onChange={e=>setValues(v=>({...v,[f.key]:f.type==='tel'?e.target.value.replace(/\D/g,'').slice(0,10):e.target.value}))}/>}</label>)}{error&&<p role="alert" className="mp-form-error">{error}</p>}<footer><button type="button" disabled={busy} onClick={()=>setMode(null)}>Cancel</button><button className="primary-button" disabled={busy}>{busy?'Working?':mode==='delete'?'Delete permanently':'Save changes'}</button></footer></form></dialog>,document.body)}</span>;
}
