"use client";

import Image from "next/image";
import { onAuthStateChanged, signOut } from "firebase/auth";
import { useEffect, useState } from "react";
import { auth } from "@/lib/firebase-client";

type Profile={agent_code:string;status:string;kyc_status:string;joining_date:string;partner_type:string;region:string|null;users:{full_name:string;phone:string}};
export default function PartnerHome(){const[profile,setProfile]=useState<Profile|null>(null);const[error,setError]=useState("");useEffect(()=>onAuthStateChanged(auth,async(user)=>{if(!user)return location.replace("/partner/login");const tokenResult=await user.getIdTokenResult(true);if(tokenResult.claims.mustChangePassword)return location.replace("/partner/change-password");const response=await fetch("/api/partner/me",{headers:{Authorization:`Bearer ${tokenResult.token}`}});if(!response.ok)return setError("Your partner profile could not be loaded.");setProfile((await response.json()).data)}),[]);return <main className="partner-home"><header><Image src="/brand/magikpolicy-logo.png" alt="MagikPolicy" width={420} height={140}/><button onClick={async()=>{await signOut(auth);location.replace("/partner/login")}}>Sign out</button></header>{error?<section className="partner-home-card"><h1>Profile unavailable</h1><p>{error}</p></section>:!profile?<section className="partner-home-card"><p>Loading your workspace…</p></section>:<><section className="partner-welcome"><p className="partner-kicker">Partner workspace</p><h1>Welcome, {profile.users.full_name}</h1><p>Your MagikPolicy business account is ready.</p></section><section className="partner-summary"><article><span>Partner ID</span><strong>{profile.agent_code}</strong></article><article><span>Account status</span><strong>{profile.status}</strong></article><article><span>KYC</span><strong>{profile.kyc_status.replaceAll("_"," ")}</strong></article><article><span>Region</span><strong>{profile.region||"Not assigned"}</strong></article></section><section className="partner-home-card"><h2>Start building your insurance business</h2><p>Lead management, customers, policies, renewals, referrals and earnings will appear here as each partner module is activated.</p></section></>}</main>}
