"use client";
import { useEffect, useRef, useState, type FormEvent } from "react";
import { accessToken } from "@/lib/supabase-client";
import {PolicyFields} from "@/components/policy/policy-fields";
type Options=any;
export function LeadPolicyForm({lead,close,saved}:{lead:{id:string;name:string;contact:string|null;product_sector_id?:string|null;product_type_id?:string|null};close:()=>void;saved:()=>void}){
 const ref=useRef<HTMLDialogElement>(null),[options,setOptions]=useState<Options|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{const previous=document.activeElement as HTMLElement|null;ref.current?.showModal();const overflow=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=overflow;previous?.focus()}},[]);
 useEffect(()=>{let active=true;setError("");(async()=>{const response=await fetch("/api/partner/lead-policy",{headers:{Authorization:`Bearer ${await accessToken()}`}});const body=await response.json();if(!response.ok)throw Error(body.error);if(active)setOptions(body)})().catch(error=>{if(active)setError(error.message)});return()=>{active=false}},[attempt]);
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");try{const values=new FormData(event.currentTarget);values.set("leadId",lead.id);const response=await fetch("/api/partner/lead-policy",{method:"POST",headers:{Authorization:`Bearer ${await accessToken()}`},body:values});const body=await response.json();if(!response.ok)throw Error(body.error);saved()}catch(error){setError(error instanceof Error?error.message:"Unable to create policy")}finally{setBusy(false)}}
 return <dialog ref={ref} className="lead-policy-dialog" aria-labelledby="lead-policy-title" onCancel={event=>{event.preventDefault();if(!busy)close()}}><header><h2 id="lead-policy-title">Add New Policy</h2><button type="button" onClick={close} disabled={busy} aria-label="Close policy form">×</button></header><p><strong>{lead.name}</strong> · {lead.contact||"No mobile number"}</p><p>The policy will be submitted for admin approval. Your customer record will be linked or created automatically.</p>{error&&<p role="alert">{error}</p>}{!options?error?<button onClick={()=>setAttempt(value=>value+1)}>Try again</button>:<p role="status">Loading policy options…</p>:<form onSubmit={submit}><fieldset disabled={busy}><PolicyFields partner options={options} conversion={{leadId:lead.id,sectorId:lead.product_sector_id,productTypeId:lead.product_type_id}}/><label className="admin-form-field mp-label">Upload policy (optional)<input className="mp-control" name="policyDocument" type="file" accept="application/pdf,image/jpeg,image/png"/><small>PDF, JPG or PNG, up to 5 MB.</small></label></fieldset><footer><button type="button" onClick={close} disabled={busy}>Cancel</button><button className="mp-form-action" type="submit" disabled={busy}>{busy?"Creating…":"Create policy"}</button></footer></form>}</dialog>;
}
