"use client";
import {useCallback,useEffect,useState} from "react";
import {Copy,Download,Share2,Users,UserPlus,MessageCircle,RefreshCw} from "lucide-react";
import QRCode from "qrcode";
import {accessToken} from "@/lib/supabase-client";
import {PartnerSkeleton} from "./partner-skeleton";
type Member={depth:number;member:{id:string;agent_code:string;status:string;region:string|null;created_at:string;users:{full_name:string}}};
type Team={code:string;canInvite:boolean;expiresAt:string|null;members:Member[];total:number;counts:number[];page:number};
export function PartnerTeam(){
 const [data,setData]=useState<Team|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState(""),[page,setPage]=useState(1),[level,setLevel]=useState(0),[qr,setQr]=useState(""),[url,setUrl]=useState("");
 const load=useCallback(async()=>{setLoading(true);setError("");try{const r=await fetch("/api/partner/team?page="+page+"&level="+level,{headers:{Authorization:"Bearer "+await accessToken()},cache:"no-store"});const b=await r.json();if(!r.ok)throw Error(b.error);setData(b);setUrl(location.origin+"/invite/"+b.code);}catch(e){setError(e instanceof Error?e.message:"Unable to load your team.");}finally{setLoading(false);}},[page,level]);
 useEffect(()=>{void load()},[load]);
 useEffect(()=>{let active=true;setQr("");if(url)QRCode.toDataURL(url,{width:600,margin:4,errorCorrectionLevel:"M"}).then(v=>{if(active)setQr(v)}).catch(()=>{if(active)setNotice("QR code could not be generated. You can still copy your link.")});return()=>{active=false}},[url]);
 function download(){const a=document.createElement("a");a.href=qr;a.download="magikpolicy-partner-invite.png";a.click();}
 async function share(){try{const blob=await (await fetch(qr)).blob();const file=new File([blob],"magikpolicy-partner-invite.png",{type:"image/png"});if(navigator.canShare?.({files:[file]}))await navigator.share({files:[file],title:"Join my MagikPolicy team",text:"Register as a partner: "+url});else{download();setNotice("QR code downloaded. Attach it in your preferred app to share.");}}catch(e){if(!(e instanceof Error&&e.name==="AbortError"))setNotice("Sharing is unavailable. Please download the QR code.");}}
 if(loading)return <PartnerSkeleton view="customers"/>;
 return <div className="pt-page"><header className="pt-heading"><div><h1>My Team</h1><p>Build your network. Help more people find the protection they need.</p></div><button type="button" onClick={()=>void load()}><RefreshCw/>Refresh</button></header>
 {error?<section role="alert" className="pt-card"><p>{error}</p><button onClick={()=>void load()}>Try again</button></section>:data&&<>
 <section className="pt-invite pt-card"><div><span className="pt-icon"><UserPlus/></span><h2>Grow together with MagikPolicy</h2><p>Invite someone to become a partner in your team. They will complete registration and the usual approval process.</p><label>Your referral code<input readOnly value={data.code}/></label>{data.canInvite?<><label>Your invitation link<input readOnly value={url} onFocus={e=>e.currentTarget.select()}/></label><div className="pt-actions"><button className="pt-primary" onClick={async()=>{try{await navigator.clipboard.writeText(url);setNotice("Invite link copied.")}catch{setNotice("Select the invitation link above and copy it manually.")}}}><Copy/>Copy Invite Link</button><a href={"https://wa.me/?text="+encodeURIComponent("Join my MagikPolicy partner team: "+url)} target="_blank" rel="noopener noreferrer"><MessageCircle/>Share via WhatsApp</a></div>{data.expiresAt&&<p>Invitation valid until {new Date(data.expiresAt).toLocaleDateString("en-IN")}.</p>}</>:<p role="status">Invitations are unavailable for this account, or your team has reached the three-level limit. Contact support for help.</p>}<p className="pt-note">New partners join directly under you. Existing partners keep their current team.</p></div>{data.canInvite&&<aside>{qr?<img src={qr} width={240} height={240} alt="Scan to register as a partner in my team"/>:<p>Preparing QR code...</p>}<p>Scan to join your team</p><div className="pt-actions"><button disabled={!qr} onClick={download}><Download/>Download QR</button><button disabled={!qr} onClick={()=>void share()}><Share2/>Share QR</button></div></aside>}</section>
 <p role="status" className="pt-notice">{notice}</p><section className="pt-stats">{["Direct Partners","Level 2 Partners","Level 3 Partners"].map((label,i)=><article className="pt-card" key={label}><Users/><strong>{data.counts[i]}</strong><span>{label}</span></article>)}</section>
 <section className="pt-card"><div className="pt-heading"><div><h2>Your downline team</h2><p>View partner status and team levels.</p></div><label>Team level<select value={level} onChange={e=>{setLevel(Number(e.target.value));setPage(1)}}><option value={0}>All levels</option><option value={1}>Direct partners</option><option value={2}>Level 2</option><option value={3}>Level 3</option></select></label></div>
 {!data.members.length?<div className="pt-empty"><span className="pt-icon"><Users/></span><h3>{data.counts.some(Boolean)?"No partners at this level":"Your team starts with one invitation"}</h3><p>{data.counts.some(Boolean)?"Select another level to view your team.":"Share your link or QR code with someone ready to start their insurance business. New partners will appear here after registration."}</p></div>:<ul className="pt-members">{data.members.map(({depth,member})=><li key={member.id}><span className="pt-avatar">{member.users?.full_name?.slice(0,1)||"P"}</span><div><strong>{member.users?.full_name||"Partner"}</strong><small>{member.agent_code} ? {member.region||"Region not added"}</small></div><span>Level {depth}</span><span className="pt-status">{member.status.replaceAll("_"," ")}</span><small>Joined {new Date(member.created_at).toLocaleDateString("en-IN")}</small></li>)}</ul>}
 {data.total>20&&<div className="pt-actions"><button disabled={page<=1} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page} of {Math.ceil(data.total/20)}</span><button disabled={page*20>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div>}</section></>}
 </div>;
}
