import Image from "next/image";
import Link from "next/link";
import { ArrowRight, FileCheck2, MessageCircle, ShieldCheck, Users } from "lucide-react";
const content={
 policies:{title:"No Policies Yet",description:"Your policy portfolio starts with one customer. Help them find suitable protection and track their issued policies here.",action:"Create Your First Lead",href:"/partner/leads?create=1",steps:["Add a Lead","Explore Plans","Help Them Get Insured","Manage Their Cover"],details:["Understand your customer's needs.","Compare suitable insurance options.","Support their application and purchase.","Keep track of policies and renewals."]},
 renewals:{title:"No Renewals Due",description:"You're all caught up! Active and issued policies expiring in the next 30 days will appear here so you can help customers stay protected.",action:"View Your Policies",href:"/partner/policies",steps:["Track Policies","Review Cover","Contact Customers","Keep Them Protected"],details:["Keep policy details up to date.","Check cover before the expiry date.","Discuss their changing needs.","Help arrange timely renewals."]},
 earnings:{title:"No Earnings Yet",description:"Every customer relationship is a step forward. Start with your first lead; your commissions will appear here once recorded.",action:"Create Your First Lead",href:"/partner/leads?create=1",steps:["Add a Lead","Share Suitable Plans","Support the Purchase","Track Your Earnings"],details:["Start a conversation with a customer.","Help them understand their options.","Guide them towards the right protection.","Review recorded commissions and progress."]},
};
export function PartnerBusinessEmpty({kind}:{kind:keyof typeof content}){const c=content[kind],icons=[Users,FileCheck2,MessageCircle,ShieldCheck],tones=["blue","green","orange","violet"];return <section className="pl-empty" aria-labelledby={kind+"-empty-title"}><div className="pl-empty-hero"><Image src="/brand/partner-welcome.png" width={1536} height={1024} sizes="(max-width:600px) 90vw,480px" alt=""/><h2 id={kind+"-empty-title"}>{c.title}</h2><p>{c.description}</p><Link className="partner-start-cta" href={c.href}>{c.action}<ArrowRight aria-hidden="true"/></Link></div><div className="pl-empty-guide"><h3>How It Works</h3><ol className="partner-start-steps">{c.steps.map((title,i)=>{const Icon=icons[i];return <li key={title}><span className={"pl-empty-icon "+tones[i]}><Icon aria-hidden="true"/></span><h3>{i+1}. {title}</h3><p>{c.details[i]}</p>{i<3&&<ArrowRight className="partner-step-arrow" aria-hidden="true"/>}</li>})}</ol></div></section>}
