"use client";
import {useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {accessToken} from '@/lib/supabase-client';
import {leadStatuses,statusLabel,lostReasons,nextFollowup,activityDate,indiaDay} from '@/lib/lead-activity';
import './admin/record-actions.css';
import './lead-activity.css';
function ActivityDialog({children,close,title}:{children:React.ReactNode;close:()=>void;title:string}){
 const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const el=ref.current;el?.showModal();return()=>el?.close()},[]);
 return createPortal(<dialog ref={ref} className="record-action-dialog lead-activity-dialog" aria-label={title} onCancel={e=>{e.preventDefault();close()}}><button type="button" className="secondary-button" onClick={close} aria-label="Close">×</button><h2>{title}</h2>{children}</dialog>,document.body);
}
export function LeadStatusControl({value,onChange,className}:{value:string;onChange:(status:string,reason?:string,note?:string)=>Promise<void>;className?:string}){
 const [lost,setLost]=useState(false),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false);
 async function save(status:string,note?:string){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{await onChange(status,reason,note);setLost(false)}catch(e){setError(e instanceof Error?e.message:'Unable to update status')}finally{lock.current=false;setBusy(false)}}
 return <><select aria-label="Lead Status" className={className||`mp-control lead-status ${value}`} disabled={busy} value={value} onClick={e=>e.stopPropagation()} onChange={e=>{if(e.target.value==='lost'){setReason('');setError('');setLost(true)}else void save(e.target.value)}}>{leadStatuses.map(s=><option key={s} value={s}>{statusLabel(s)}</option>)}</select>{error&&!lost&&<p role="alert" className="mp-form-error">{error}</p>}{lost&&<ActivityDialog title="Why was this lead lost?" close={()=>{if(!busy)setLost(false)}}><form onSubmit={e=>{e.preventDefault();void save('lost',String(new FormData(e.currentTarget).get('note')||''))}}><label className="mp-label">Lost Reason *<select className="mp-control" required value={reason} onChange={e=>setReason(e.target.value)}><option value="">Select reason</option>{lostReasons.map(r=><option key={r}>{r}</option>)}</select></label><label className="mp-label">{reason==='Other'?'Reason / Notes *':'Notes'}<textarea className="mp-control" name="note" required={reason==='Other'} maxLength={4000}/></label>{error&&<p role="alert" className="mp-form-error">{error}</p>}<button className="primary-button" disabled={busy}>{busy?'Saving…':'Mark Lost'}</button></form></ActivityDialog>}</>;
}
export function LeadActivity({id,kind='internal',scope,name,onChanged}:{id:string;kind?:'internal'|'website';scope:'admin'|'partner';name:string;onChanged:()=>void}){
 const [open,setOpen]=useState(false),[data,setData]=useState<any>(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(false),[form,setForm]=useState<any>(null);const lock=useRef(false),requestId=useRef('');
 async function load(){const r=await fetch(`/api/leads/activity?${new URLSearchParams({id,kind,scope})}`,{headers:{Authorization:`Bearer ${await accessToken()}`}});const b=await r.json();if(!r.ok)throw Error(b.error);setData(b)}
 async function show(){setOpen(true);setError('');setSuccess('');try{await load()}catch(e){setError(e instanceof Error?e.message:'Unable to load activity')}}
 async function save(action:string,values:any={}){if(lock.current)return;lock.current=true;setBusy(true);setError('');setSuccess('');try{const r=await fetch('/api/leads/activity',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${await accessToken()}`},body:JSON.stringify({id,kind,scope,action,...values})});const b=await r.json();if(!r.ok)throw Error(b.error);setForm(null);await load();setSuccess('Follow-up saved.');onChanged()}catch(e){setError(e instanceof Error?e.message:'Unable to save follow-up')}finally{lock.current=false;setBusy(false)}}
 function schedule(row:any={}){requestId.current=crypto.randomUUID();setForm(row);setError('')}
 const next=data?nextFollowup({...data.lead,followups:data.followups}):null,closed=data&&['converted','lost'].includes(data.lead.status);
 return <><button type="button" className="secondary-button" onClick={e=>{e.stopPropagation();void show()}}>Follow-up</button>{open&&<ActivityDialog title={`${name} — Lead Details`} close={()=>{if(!busy){setOpen(false);setForm(null);setData(null)}}}>{error&&<p role="alert" className="mp-form-error">{error}</p>}{success&&<p role="status">{success}</p>}{!data&&!error&&<p>Loading…</p>}{data&&<><h3>Current status: {statusLabel(data.lead.status)}</h3>{data.lead.lost_reason&&<p>Lost reason: {data.lead.lost_reason} {data.lead.lost_note}</p>}<h3>Next Follow-up</h3>{next?<p><strong>{activityDate(next.scheduled_at)} IST</strong><br/>{next.followup_type}<br/>{next.note}{Date.parse(next.scheduled_at)<Date.now()&&<strong> — Overdue</strong>}</p>:<p>{closed?'Closed lead — no follow-up required.':'No follow-up scheduled.'}</p>}{next&&<><button className="secondary-button" disabled={busy} onClick={()=>void save('complete',{followupId:next.id})}>Mark Complete</button><button className="secondary-button" disabled={busy} onClick={()=>schedule(next)}>Reschedule</button></>}{!closed&&<button className="primary-button" disabled={busy} onClick={()=>schedule()}>Schedule Follow-up</button>}
 {form&&<form key={requestId.current} onSubmit={e=>{e.preventDefault();const v=Object.fromEntries(new FormData(e.currentTarget));void save(form.id?'reschedule':'schedule',{followupId:form.id,requestId:requestId.current,scheduledAt:`${v.date}T${v.time}:00+05:30`,followupType:v.type,note:v.note})}}><h3>{form.id?'Reschedule':'Schedule Follow-up'}</h3><p>All dates and times are in India Standard Time (IST).</p><label className="mp-label">Follow-up Date *<input className="mp-control" type="date" name="date" required defaultValue={form.scheduled_at?indiaDay(form.scheduled_at):''}/></label><label className="mp-label">Follow-up Time *<input className="mp-control" type="time" name="time" required defaultValue={form.scheduled_at?new Date(form.scheduled_at).toLocaleTimeString('en-GB',{timeZone:'Asia/Kolkata',hour:'2-digit',minute:'2-digit'}):''}/></label><label className="mp-label">Follow-up Type *<select className="mp-control" name="type" required defaultValue={form.followup_type||''}><option value="">Select type</option>{['call','whatsapp','email','meeting','other'].map(t=><option key={t} value={t}>{statusLabel(t)}</option>)}</select></label><label className="mp-label">Note<textarea className="mp-control" name="note" maxLength={4000} defaultValue={form.note||''}/></label><button className="primary-button" disabled={busy}>{busy?'Saving…':'Save Follow-up'}</button><button type="button" className="secondary-button" disabled={busy} onClick={()=>setForm(null)}>Cancel</button></form>}
 <h3>Activity / History</h3>{!data.followups.length&&!data.history.length&&<p>No activity recorded yet.</p>}{data.followups.map((f:any)=><article key={f.id}><strong>{activityDate(f.scheduled_at)} IST — {statusLabel(f.followup_type)}</strong><p>{f.note}</p><p>{statusLabel(f.status)} · By {f.creator?.full_name||f.created_by} · Created {activityDate(f.created_at)}</p>{f.completed_at&&<p>Completed {activityDate(f.completed_at)} by {f.completer?.full_name||f.completed_by}</p>}{f.status==='scheduled'&&<><button className="secondary-button" disabled={busy} onClick={()=>void save('complete',{followupId:f.id})}>Mark Complete</button>{!closed&&<button className="secondary-button" disabled={busy} onClick={()=>schedule(f)}>Reschedule</button>}<button className="secondary-button" disabled={busy} onClick={()=>void save('cancel',{followupId:f.id})}>Cancel follow-up</button></>}</article>)}{data.history.map((h:any)=><article key={h.id}><strong>{statusLabel(h.previous_status)} ? {statusLabel(h.new_status)}</strong><p>{activityDate(h.changed_at)} IST · Changed by {h.actor?.full_name||h.changed_by||'System / legacy'}</p></article>)}</>}</ActivityDialog>}</>;
}
export function NextFollowup({lead}:{lead:any}){const next=nextFollowup(lead);return <span>{next?<>{activityDate(next.scheduled_at)} IST{Date.parse(next.scheduled_at)<Date.now()&&<strong> · Overdue</strong>}</>:'—'}</span>}
