"use client";
import {useEffect,useId,useState} from "react";
import {accessToken} from "@/lib/supabase-client";
import "./lead-customer-fields.css";
export function LeadCustomerFields({scope,initial,locked=false,onSelect}:{scope:'admin'|'partner';initial?:any;locked?:boolean;onSelect?:(row:any)=>void}){
 const [name,setName]=useState(initial?.name||''),[contact,setContact]=useState(initial?.contact||''),[selected,setSelected]=useState(initial?.id||''),[matches,setMatches]=useState<any[]>([]),[focused,setFocused]=useState(false),[error,setError]=useState(''),[loading,setLoading]=useState(false),[index,setIndex]=useState(-1);const id=useId();
 useEffect(()=>{setMatches([]);setIndex(-1);if(!focused||selected||!name.trim())return;const controller=new AbortController();setLoading(true);const timer=setTimeout(async()=>{try{const r=await fetch(`/api/customer-search?scope=${scope}&q=${encodeURIComponent(name)}`,{signal:controller.signal,headers:{Authorization:`Bearer ${await accessToken()}`}});const b=await r.json();if(!r.ok)throw Error(b.error);if(!controller.signal.aborted){setMatches(b.data);setError('')}}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Customer search failed')}finally{if(!controller.signal.aborted)setLoading(false)}},250);return()=>{clearTimeout(timer);controller.abort()}},[name,focused,selected,scope]);
 function choose(row:any){onSelect?.(row);setName(row.name);setContact(row.contact||'');setSelected(row.id);setMatches([]);setFocused(false)}
 return <><input type="hidden" name="customerId" value={selected}/><label className="mp-label lead-customer-search">Customer name<input className="mp-control" name="name" required minLength={2} autoComplete="off" readOnly={locked} value={name} role="combobox" aria-autocomplete="list" aria-expanded={focused&&matches.length>0} aria-controls={id} aria-activedescendant={index>=0?`${id}-${index}`:undefined} onFocus={()=>setFocused(true)} onBlur={()=>setFocused(false)} onChange={e=>{setName(e.target.value);setSelected('')}} onKeyDown={e=>{if(e.key==='Escape')setFocused(false);if(e.key==='ArrowDown'){e.preventDefault();setIndex(i=>Math.min(i+1,matches.length-1))}if(e.key==='ArrowUp'){e.preventDefault();setIndex(i=>Math.max(i-1,0))}if(e.key==='Enter'&&focused&&matches[index]){e.preventDefault();choose(matches[index])}}}/>{focused&&!selected&&name.trim()&&<span className="lead-customer-results" id={id} role="listbox">{loading?<span role="status">Searching?</span>:matches.length?matches.map((row,i)=><button type="button" role="option" aria-selected={index===i} id={`${id}-${i}`} key={row.id} onMouseDown={e=>e.preventDefault()} onClick={()=>choose(row)}><strong>{row.name}</strong><small>{row.contact||'No mobile number'}</small></button>):<span>{error||'No matching customers. You can enter a new lead.'}</span>}</span>}</label><label className="mp-label">Mobile number<span className="mp-input-group mp-phone-group"><span className="mp-country">+91</span><input className="mp-control" name="contact" value={contact} onChange={e=>setContact(e.target.value.replace(/\D/g,'').slice(0,10))} required inputMode="numeric" maxLength={10} minLength={10} pattern="[0-9]{10}"/></span></label></>;
}
