"use client";
import Link from "next/link";
import { useParams } from "next/navigation";
import { useEffect,useState } from "react";
import { accessToken } from "@/lib/supabase-client";

type Item={id:string;status:string;premium:number;coverage:number|null;created_at:string;products:{name:string}|null;insurers:{name:string}|null;policy_number?:string;quote_reference?:string;expiry_date?:string};
type Customer={id:string;user_id:string|null;name:string;contact:string|null;email:string|null;address:string|null;created_at:string;updated_at:string;users:{status:string}|null;policies:Item[];quotes:Item[];notes:Array<{id:string;body:string;created_at:string}>};
const money=new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:0});
export default function CustomerDetailPage(){const{id}=useParams<{id:string}>(),[customer,setCustomer]=useState<Customer|null>(null),[error,setError]=useState("");useEffect(()=>{let active=true;(async()=>{const token=await accessToken(),response=await fetch(`/api/admin/customers/${id}`,{headers:{Authorization:`Bearer ${token}`}}),body=await response.json();if(!active)return;if(response.ok)setCustomer(body.data);else setError(body.error||"Customer could not be loaded.")})();return()=>{active=false}},[id]);if(error)return <div className="customer-detail-state"><h1>Customer unavailable</h1><p>{error}</p><Link href="/admin/customers">Back to customers</Link></div>;if(!customer)return <div className="customer-detail-state">Loading customer details…</div>;return <div className="customer-detail-page"><Link className="customer-back-link" href="/admin/customers">← Back to customers</Link><header><span className="customer-detail-avatar">{customer.name.slice(0,2).toUpperCase()}</span><div><p className="admin-eyebrow">Customer profile</p><h1>{customer.name}</h1><span>Customer since {new Date(customer.created_at).toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"})}</span></div><i className={`customer-account-status ${customer.users?.status||"legacy"}`}>{customer.user_id?(customer.users?.status||"active"):"CRM only"}</i></header><section className="customer-detail-grid"><article><h2>Contact Information</h2><dl><div><dt>Email address</dt><dd>{customer.email||"Not provided"}</dd></div><div><dt>Mobile number</dt><dd>{customer.contact||"Not provided"}</dd></div><div><dt>Address</dt><dd>{customer.address||"Not provided"}</dd></div><div><dt>Account type</dt><dd>{customer.user_id?"Registered customer":"CRM customer"}</dd></div></dl></article><article><h2>Overview</h2><div className="customer-detail-stats"><span><small>Policies</small><strong>{customer.policies.length}</strong></span><span><small>Quotes</small><strong>{customer.quotes.length}</strong></span><span><small>Total premium</small><strong>{money.format(customer.policies.reduce((sum,item)=>sum+Number(item.premium||0),0))}</strong></span></div></article></section><CustomerItems title="Policies" items={customer.policies} empty="No policies are associated with this customer."/><CustomerItems title="Quotes" items={customer.quotes} empty="No quotes are associated with this customer."/>{customer.notes.length>0&&<section className="customer-record-card"><h2>Customer Notes</h2>{customer.notes.map(note=><div className="customer-note" key={note.id}><p>{note.body}</p><small>{new Date(note.created_at).toLocaleString("en-IN")}</small></div>)}</section>}</div>}
function CustomerItems({title,items,empty}:{title:string;items:Item[];empty:string}){return <section className="customer-record-card"><h2>{title}</h2>{!items.length?<p className="customer-empty">{empty}</p>:<div className="customer-item-list">{items.map(item=><article key={item.id}><div><strong>{item.products?.name||"Insurance"}</strong><small>{item.insurers?.name||"Insurer not assigned"}</small></div><div><span>Reference</span><strong>{item.policy_number||item.quote_reference}</strong></div><div><span>Premium</span><strong>{money.format(item.premium||0)}</strong></div><div><span>Status</span><i className={`status-pill ${item.status}`}>{item.status}</i></div></article>)}</div>}</section>}
