import {NextRequest,NextResponse} from "next/server";
import {verifyRequestToken} from "@/lib/auth-server";
import {ensureAdminPermission} from "@/lib/rbac";
import {supabaseServer} from "@/lib/supabase-server";
import {productSchema,publicationErrors,productValidationMessages} from "@/lib/product-catalog";
import {z} from "zod";
async function catalogUser(req:NextRequest,action:string){const user=await verifyRequestToken(req.headers.get('authorization'));return user&&await ensureAdminPermission(user.uid,user.email,'catalog',action)?user:null;}
export async function GET(req:NextRequest){if(!await catalogUser(req,'view'))return NextResponse.json({error:'Forbidden'},{status:403});const db=supabaseServer();const results=await Promise.all([db.from('products').select('*,plans(*),product_documents(*)').order('name'),db.from('categories').select('id,name').eq('active',true).order('name'),db.from('product_types').select('id,name,category_id').order('name'),db.from('insurers').select('id,name').eq('active',true).order('name')]);const error=results.find(r=>r.error)?.error;if(error)return NextResponse.json({error:error.message},{status:500});return NextResponse.json({data:results[0].data,sectors:results[1].data,types:results[2].data,insurers:results[3].data},{headers:{'Cache-Control':'private, no-store'}});}
export async function POST(req:NextRequest){const user=await catalogUser(req,'edit');if(!user)return NextResponse.json({error:'Forbidden'},{status:403});try{const input=productSchema.parse(await req.json());const {data,error}=await supabaseServer().rpc('save_catalog_product',{p_id:input.id||null,p_actor:user.uid,p_data:input});if(error)return NextResponse.json({error:error.code==='23505'?'This URL slug is already in use.':error.message},{status:400});return NextResponse.json({id:data});}catch(e){return NextResponse.json({error:e instanceof z.ZodError?productValidationMessages(e.issues).join('\n'):'Unable to save product'},{status:400})}}
export async function PATCH(req:NextRequest){const user=await catalogUser(req,'edit');if(!user)return NextResponse.json({error:'Forbidden'},{status:403});try{const input=z.object({id:z.string().uuid(),status:z.enum(['published','archived']),expectedUpdatedAt:z.string(),reviewed:z.boolean().optional()}).parse(await req.json()),db=supabaseServer();const {data:product,error:readError}=await db.from('products').select('*').eq('id',input.id).single();if(readError)return NextResponse.json({error:'Product not found'},{status:404});if(input.status==='published'){const missing=publicationErrors(product);if(!input.reviewed||missing.length)return NextResponse.json({error:missing.length?'Complete: '+missing.join(', '):'Confirm you reviewed the product against the source documents'},{status:400});}const {data,error}=await db.from('products').update({publication_status:input.status,reviewed_at:new Date().toISOString(),reviewed_by:user.uid,updated_at:new Date().toISOString()}).eq('id',input.id).eq('updated_at',input.expectedUpdatedAt).select('id').maybeSingle();if(error)return NextResponse.json({error:error.message},{status:400});return data?NextResponse.json({ok:true}):NextResponse.json({error:'This product changed. Refresh before publishing.'},{status:409});}catch{return NextResponse.json({error:'Invalid publication request'},{status:400})}}
