import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { verifyRequestToken } from "@/lib/firebase-admin";
import { ensureAdminPermission } from "@/lib/rbac";
import { supabaseServer } from "@/lib/supabase-server";

async function authorize(request:NextRequest,action:string){const user=await verifyRequestToken(request.headers.get("authorization"));return user&&await ensureAdminPermission(user.uid,user.email,"quotes_policies",action)}
async function options(){const db=supabaseServer(),[sectors,types,products,insurers,plans,customers,agents]=await Promise.all([db.from("categories").select("id,name").eq("active",true).order("sort_order"),db.from("product_types").select("id,name,category_id").eq("active",true).order("sort_order"),db.from("products").select("id,name,category_id").order("name"),db.from("insurers").select("id,name").eq("active",true).order("name"),db.from("plans").select("id,name,product_id,insurer_id").order("name"),db.from("customers").select("id,name").order("name"),db.from("agents").select("id,agent_code,users:users!agents_user_id_fkey(full_name)").order("agent_code")]);return{sectors:sectors.data||[],productTypes:types.data||[],products:products.data||[],insurers:insurers.data||[],plans:plans.data||[],customers:customers.data||[],agents:agents.data||[]}}

export async function GET(request:NextRequest,{params}:{params:Promise<{id:string}>}){if(!await authorize(request,"view"))return NextResponse.json({error:"forbidden"},{status:403});const{id}=await params,db=supabaseServer(),{data,error}=await db.from("policies").select("*").eq("id",id).maybeSingle();if(error||!data)return NextResponse.json({error:error?.message||"Policy not found"},{status:404});return NextResponse.json({data,options:await options()})}

const schema=z.object({policyNumber:z.string().trim().min(3).max(80),customerId:z.string().uuid(),agentId:z.string().uuid(),sectorId:z.string().uuid(),productTypeId:z.string().uuid(),productId:z.string().uuid().optional().or(z.literal("")),insurerId:z.string().uuid(),planId:z.string().uuid().optional().or(z.literal("")),premium:z.coerce.number().positive(),coverage:z.union([z.coerce.number().nonnegative(),z.literal("")]).optional(),startDate:z.string().date(),expiryDate:z.string().date(),businessType:z.enum(["fresh","port","renew"]),status:z.enum(["proposal","pending","issued","active","expired","cancelled"])}).refine(v=>v.expiryDate>v.startDate,{message:"Expiry date must be after the start date",path:["expiryDate"]});
export async function PATCH(request:NextRequest,{params}:{params:Promise<{id:string}>}){if(!await authorize(request,"edit"))return NextResponse.json({error:"forbidden"},{status:403});try{const{id}=await params,input=schema.parse(await request.json()),db=supabaseServer();const[{data:type},{data:product},{data:plan},{data:current}]=await Promise.all([db.from("product_types").select("category_id").eq("id",input.productTypeId).maybeSingle(),input.productId?db.from("products").select("category_id").eq("id",input.productId).maybeSingle():Promise.resolve({data:null}),input.planId?db.from("plans").select("product_id,insurer_id").eq("id",input.planId).maybeSingle():Promise.resolve({data:null}),db.from("policies").select("status").eq("id",id).maybeSingle()]);if(!type||type.category_id!==input.sectorId)return NextResponse.json({error:"Product type does not belong to the selected sector."},{status:400});if(input.productId&&(!product||product.category_id!==input.sectorId))return NextResponse.json({error:"Product does not belong to the selected sector."},{status:400});if(input.planId&&(!input.productId||!plan||plan.product_id!==input.productId||plan.insurer_id!==input.insurerId))return NextResponse.json({error:"Plan does not belong to the selected product and insurer."},{status:400});const{data,error}=await db.from("policies").update({policy_number:input.policyNumber,customer_id:input.customerId,agent_id:input.agentId,category_id:input.sectorId,product_type_id:input.productTypeId,product_id:input.productId||null,insurer_id:input.insurerId,plan_id:input.planId||null,premium:input.premium,coverage:input.coverage===""?null:input.coverage??null,start_date:input.startDate,expiry_date:input.expiryDate,business_type:input.businessType,status:input.status,updated_at:new Date().toISOString()}).eq("id",id).select().single();if(error)return NextResponse.json({error:error.code==="23505"?"This policy number already exists.":error.message},{status:400});if(current&&current.status!==input.status)await db.from("policy_status_history").insert({policy_id:id,from_status:current.status,to_status:input.status});return NextResponse.json({data})}catch(error){return NextResponse.json({error:error instanceof z.ZodError?error.issues[0]?.message:"Could not update policy"},{status:400})}}
